### PR TITLE
Port cross-plat ProcessExtensions from CLI

### LINKED ISSUE #434: Ctrl-C process termination throws on Linux
Ran a build, thought better of it. Got this:

```
^CAttempting to cancel the build...
/home/raines/src/corefx/build.proj(40,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: The "Exec" task failed unexpectedly.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018: System.DllNotFoundException: Unable to load DLL 'KERNEL32.DLL': The specified module could not be found.
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:  (Exception from HRESULT: 0x8007007E)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.OpenProcess(eDesiredAccess dwDesiredAccess, Boolean bInheritHandle, Int32 dwProcessId)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.KillTree(Int32 processIdToKill)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.KillToolProcessOnTimeout(Process proc, Boolean isBeingCancelled)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.TerminateToolProcess(Process proc, Boolean isBeingCancelled)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/home/raines/src/corefx/build.proj(40,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

We should at the very least not throw and probably should have a better implementation of this.

### LINKED ISSUE #757: MSBuild is trying to PInvoke to Kernel32 on Linux
I have this in my target:
```
 <Exec Command="python" />
```
Since I did not pass any parameters it started REPL and blocked the build. So I pressed Ctrl+C and MSBuild failed trying to PInvoke into Kernel32.dll

```
Build started 7/1/16 11:39:17 PM.
The target "Initialize" listed in a BeforeTargets attribute at "/home/moozzyk/source/libuv-build/.build/KoreBuild/src/Microsoft.AspNetCore.Build/targets/Initialize.targets (97,79)" does not exist in the project, and will be ignored.
Project "/home/moozzyk/source/libuv-build/makefile.proj" on node 1 (default targets).
BuildLinux:
  Linux, Platform: Linux
  python
  Python 2.7.6 (default, Jun 22 2015, 17:58:13)
  [GCC 4.8.2] on linux2
  Type "help", "copyright", "credits" or "license" for more information.
^C  >>>
  KeyboardInterrupt
Attempting to cancel the build...
/home/moozzyk/source/libuv-build/makefile.proj(16,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018: The "Exec" task failed unexpectedly.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018: System.DllNotFoundException: Unable to load DLL 'KERNEL32.DLL': The specified module could not be found.
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:  (Exception from HRESULT: 0x8007007E)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.OpenProcess(eDesiredAccess dwDesiredAccess, Boolean bInheritHandle, Int32 dwProcessId)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.KillTree(Int32 processIdToKill)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.KillToolProcessOnTimeout(Process proc, Boolean isBeingCancelled)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/home/moozzyk/source/libuv-build/makefile.proj(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
Done Building Project "/home/moozzyk/source/libuv-build/makefile.proj" (default targets) -- FAILED.
```

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Current implementation of KillTree was tied to Windows Kernel32.dll P/Invocation.

This ports the Unix implementation of same from dotnet/cli repo:
https://github.com/dotnet/cli/blob/04f40f9/test/Microsoft.DotNet.Tools.Tests.Utilities/ProcessExtensions.cs
(not sure if there is a better way to consume it as a package instead of copy-pasta :spaghetti:?)

Fix #434
Fix #757

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@rainersigwald,
this also fixes the OSX build break in #676 -- the primary reason I ended up with this fix. :smile_cat:

**Comment by jasonwilliams200OK** [comment]
@rainersigwald, the Windows build is fixed, ready for review. PTAL. :)

File: src/Utilities/ToolTask.cs [hunk 1]
```diff
@@ -1091,17 +1091,6 @@ private void KillToolProcessOnTimeout(Process proc, bool isBeingCancelled)
...
-                    // issue the kill command
-                    NativeMethodsShared.KillTree(proc.Id);
-                }
-                catch (InvalidOperationException)
-                {
-                    // The process already exited, which is fine,
-                    // just continue.
-                }
-
                 // wait until the process finishes exiting/getting killed.
```
Comment (jasonwilliams200OK) [inline src/Utilities/ToolTask.cs]: Moved that comment to `ProcessExtensions.cs`.

**Comment by rainersigwald** [comment]
I agree that the copy-🍝 isn't great, but I think it's the best we can do right now. Can you please fix the broken link in the commit message, though? I think the `t` in `test` is missing.

**Comment by jasonwilliams200OK** [comment]
@rainersigwald, fixed the broken `t` in commit message as well as the description. :)

File: src/Utilities/ProcessExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+                        }
+                    }
+                }
+            }
+        }
+
+        private static void KillProcessUnix(int processId, int timeout)
+        {
+            string stdout;
+            RunProcessAndWaitForExit(
```
Comment (radical) [inline src/Utilities/ProcessExtensions.cs]: The `timeout` in `KillTree` is meant for the killing the tool process and it's children. But this is using the timeout for the process running the `kill` command itself! Also, why launch all these processes. I wonder whether we could use the `signal(3)` syscall, and do `SIGTERM+timeout+SIGKILL` on the actual tool and children processes.

Comment (rainersigwald) [inline src/Utilities/ProcessExtensions.cs]: Hah, I was just typing up a comment about the dual meanings of `timeout`. I think it'd be better to have a fairly short timeout for the `kill` that's isolated from the "wait X to ensure that everything's done".

For using `signal(3)`, that does seem like a cleaner approach--but will it be as multi-platform-friendly? My years on Windows don't give me a good sense here. I can understand the current maybe-inefficient `kill` code.

---
In reply to: [74337936](https://github.com/Microsoft/msbuild/pull/886#discussion_r74337936) [](ancestors = 74337936)

Comment (radical) [inline src/Utilities/ProcessExtensions.cs]: I was suggesting the `signal(3)` approach for the Unix code path actually.

**Comment by radical** [comment]
> Current implementation of KillTree was tied to Windows Kernel32.dll P/Invocation.
> This removes the current implementation and ports one from dotnet/cli repo:

Um that gives me the impression that the implementation for `KillTree` is being removed, which is not the case.

File: src/Utilities/ProcessExtensions.cs (hunk 2 above)
Comment (jasonwilliams200OK) [inline src/Utilities/ProcessExtensions.cs]: I have changed it so the timeout will only be used to wait for this process.
Regarding the issuing of signal(3) vs. shelling out the kill command, IMO, this is a port of what CLI is using to unblock couple of issues. We can latest evaluate whether it makes sense to P/Invoke syscall and how much beneficial would that actually be in real world example.

**Comment by jasonwilliams200OK** [comment]
> that gives me the impression

That was a left over my first attempt when I made this patch on Mac: https://github.com/jasonwilliams200OK/msbuild/commit/384e15dd110439dd11ee3478d4c693e4ab484ad1

That failed on Windows CI. Then i spun up the Windows VM and found that some tests are to tied to existing the Windows implementation of KillTree method which is P/Invoking kernel32 process create. Therefore, I kept that helper alive to keep all existing tests satisfied.

Updated the commit log and description.

File: src/Utilities/ProcessExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+using System.Diagnostics;
+using System.IO;
+using System.Runtime.InteropServices;
+using Microsoft.Build.Shared;
+
+namespace Microsoft.Build.Utilities
+{
+    internal static class ProcessExtensions
+    {
+#if !RUNTIME_TYPE_NETCORE
```
Comment (radical) [inline src/Utilities/ProcessExtensions.cs]: For a Mono build, this would be true and so `_isWindows=true`, which would be incorrect. Mono build of msbuild could run on !windows platforms too!

File: src/Utilities/ProcessExtensions.cs [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+        private static readonly bool _isWindows = true;
+#else
+        private static readonly bool _isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
+#endif
+
+        public static void KillTree(this Process process, int timeout)
+        {
+            string stdout;
```
Comment (radical) [inline src/Utilities/ProcessExtensions.cs]: unused

Comment (jasonwilliams200OK) [inline src/Utilities/ProcessExtensions.cs]: Removed

File: src/Utilities/ProcessExtensions.cs (hunk 3 above)
Comment (jasonwilliams200OK) [inline src/Utilities/ProcessExtensions.cs]: Fixed

**Comment by AndyGerlicher** [comment]
LGTM, thanks a lot for the contribution!

**Comment by cdmihai** [comment]
LGTM
