### PR TITLE
Don't fail deserialization of item-spec project item metadata

### LINKED ISSUE #5225: Multi-proc build fails with ArgumentException if the CreateItem task is used
### Steps to reproduce

1.proj
```xml
<Project DefaultTargets="Build">
    <Target Name="Build">
        <MSBuild Projects="2.proj" Targets="Build" />
    </Target>
</Project>
```
2.proj
```xml
<Project DefaultTargets="Build">
    <Target Name='Build' Returns="@(x)">
        <CreateItem Include='$(programfiles)\reference assemblies\**\*.dll;'>
            <Output TaskParameter='Include' ItemName='x' />
        </CreateItem>
    </Target>
</Project>
```

build with
```
set MSBUILDNOINPROCNODE=1
set MSBUILDTARGETRESULTCOMPRESSIONTHRESHOLD=0

msbuild.exe 1.proj /clp:ShowCommandLine /m:1 /verbosity:n /nr:false /bl /fl /flp:v=diagnostic
```
### Expected behavior
Build succeeds.

### Actual behavior
```
error MSB4018: The "MSBuild" task failed unexpectedly.
error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
error MSB4018: System.ArgumentException: The "RecursiveDir" name is reserved, and cannot be used.
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 482
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, Exception innerException, String resourceName, Object arg0) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 614
error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(Boolean condition, String resourceName, Object arg0) in C:\src\msbuild\src\Shared\ErrorUtilities.cs:line 515
error MSB4018:    at Microsoft.Build.Execution.ProjectMetadataInstance..ctor(String name, String escapedValue, Boolean allowItemSpecModifiers) in C:\src\msbuild\src\Build\Instance\ProjectMetadataInstance.cs:line 72
error MSB4018:    at Microsoft.Build.Execution.ProjectMetadataInstance..ctor(String name, String escapedValue) in C:\src\msbuild\src\Build\Instance\ProjectMetadataInstance.cs:line 45
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.TranslateWithInterning(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 1620
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem..ctor(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 859
error MSB4018:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.FactoryForDeserialization(ITranslator translator, LookasideStringInterner interner) in C:\src\msbuild\src\Build\Instance\ProjectItemInstance.cs:line 1581
error MSB4018:    at Microsoft.Build.Execution.TargetResult.ItemsStore.DecompressItems() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 511
error MSB4018:    at Microsoft.Build.Execution.TargetResult.ItemsStore.get_Items() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 426
error MSB4018:    at Microsoft.Build.Execution.TargetResult.get_Items() in C:\src\msbuild\src\Build\BackEnd\Shared\TargetResult.cs:line 96
error MSB4018:    at Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__58.MoveNext() in C:\src\msbuild\src\Build\BackEnd\Components\RequestBuilder\TaskHost.cs:line 942
```

### Environment data
`msbuild /version` output:

```
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.12403
```

as well as current master (9f3e4e72).

### PR DESCRIPTION
**Pull request by ladipro**
The logic to decompress large target results was refusing to rehydrate project item metadata categorized as "item-specs". In particular, the `RecursiveDir` metadatum is explicitly set by the CreateItem task and falls into this category, causing the build to fail if certain conditions are met:
1. The build is out-of-proc.
2. The number of target results moved cross-proc meets the compression threshold.

It seems unnecessary to do elaborate validation on this codepath. We implicitly trust the serialized data. Fixing the issue by relaxing the checks so that compressed item-spec metadata can be deserialized.

Fixes #5225

### CODE REVIEW

File: src/Build/Instance/ProjectItemInstance.cs [hunk 1]
```diff
@@ -1617,7 +1617,7 @@ internal void TranslateWithInterning(ITranslator translator, LookasideStringInte
                         {
                             int key = translator.Reader.ReadInt32();
                             int value = translator.Reader.ReadInt32();
-                            _directMetadata.Set(new ProjectMetadataInstance(interner.GetString(key), interner.GetString(value)));
+                            _directMetadata.Set(new ProjectMetadataInstance(interner.GetString(key), interner.GetString(value), true /* allow built-in metadata names */));
```
Comment (rainersigwald) [inline src/Build/Instance/ProjectItemInstance.cs:1620]: nit: for new code we generally prefer
```suggestion
                            _directMetadata.Set(new ProjectMetadataInstance(interner.GetString(key), interner.GetString(value), allowItemSpecModifiers: true));
```

Although in this case your comment is clearer than the name!

Comment (ladipro) [reply src/Build/Instance/ProjectItemInstance.cs]: Fixed as suggested, thanks!

**Comment by ladipro** [comment]
I can reproduce the hang when running macOS Mono tests locally, it appears to be caused by the new test in this PR. I am investigating.
