### PR TITLE
Modifying CodeTaskFactory to create the TMP folder.

### LINKED ISSUE #328: When %TEMP% points to a nonexistent folder, CodeTaskFactory fails
CodeTaskFactory is implemented by emitting source files into `%TEMP%`, then building them.  If `TEMP` is set but the directory does not exist, this can cause a failure.

We could just create the folder before trying to write to it.

### PR DESCRIPTION
**Pull request by AndyGerlicher**
- Check to see if the TMP folder exists before calling CompileAssemblyFromSource.
 - Added unit test to cover scenario where the TMP path doesn't exist.
Closes #328

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Easy fix, but doesn't address the larger issue of any Path.GetTempPath() could do this. We could audit our code for this, but this ended up being in [.NET](http://referencesource.microsoft.com/#System/compmod/system/codedom/compiler/CompilerParameters.cs,a94d20b2939b4cab). We could do this on process or build start I suppose?

File: src/XMakeTasks/CodeTaskFactory.cs [hunk 1]
```diff
@@ -771,6 +771,16 @@ private Assembly CompileInMemoryAssembly()
                 if (!s_compiledTaskCache.TryGetValue(fullSpec, out existingAssembly))
                 {
                     // Invokes compilation. 
+
+                    // Note: CompileAssemblyFromSource uses Path.GetTempPath() directory, but will not create it. In some cases 
+                    // this will throw inside CompileAssemblyFromSource. To work around this, ensure the temp directory exists. 
+                    // See: https://github.com/Microsoft/msbuild/issues/328
+                    var tempPath = Path.GetTempPath();
+                    if (!Directory.Exists(tempPath))
```
Comment (rainersigwald) [inline src/XMakeTasks/CodeTaskFactory.cs]: No need to check for existence.  Just unconditionally create it, which will return success even if it already existed.

**Comment by rainersigwald** [comment]
Agree that this isn't a great solution for all of the possible problems of a missing directory, but it at least fixes one case of bad behavior we have.

I don't think it's unreasonable to ask the CLR to create the directory, but it looks like on Windows these are very thin wrappers around `kernel32` functionality, so I'm guessing that won't happen.

LGTM.

**Comment by rainersigwald** [comment]
Spoke too soon.  The test failure was because of a short-path issue.  Boo, hiss.

File: src/XMakeTasks/CodeTaskFactory.cs (hunk 1 above)
Comment (AndyGerlicher) [inline src/XMakeTasks/CodeTaskFactory.cs]: I did that first, but read through the code for [CreateDirectory](http://referencesource.microsoft.com/mscorlib/a.html#5c99436f88797b6a) and it looked like some small differences in permissions it checked before it checks for Exists. The last thing I wanted was to throw here for something like that.

Looks like there's a stackoverflow question on [this](http://stackoverflow.com/questions/27575384/c-sharp-directory-createdirectory-path-should-i-check-if-path-exists-first) and just CreateDirectory appears to be the winner. But not without some dissent :). I imagine just CreateDirectory is fine, just overly paranoid.

Comment (rainersigwald) [inline src/XMakeTasks/CodeTaskFactory.cs]: I don't feel strongly about it.  The usual argument is that you introduce a timing issue between the check and the action, but that doesn't seem to be a big problem here because there's a hole between directory and file creation anyway.

**Comment by AndyGerlicher** [comment]
Added Path.GetFullPath to the %TMP% when comparing, fixed the CI build.
