### PR TITLE
Slnf from other directory Fixes #5431

### LINKED ISSUE #5431: Building solution filter (slnf) crashes msbuild.exe if invoked from any other path
### Steps to reproduce

1. git clone https://github.com/jimmylewis/SolutionFilterSample
2. cd SolutionFilterSample\SolutionFilterSample (the project folder)
3. msbuild ..\SolutionFilter.slnf

### Expected behavior
Build the solution filter (contains 1 project).  Works fine if building from directory containing slnf file.

### Actual behavior
MSBuild crashes:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.IO.FileNotFoundException: Could not find file 'C:\Users\jamlew\Source\Repos\SolutionFilterSample\SolutionFilterSample\SolutionFilterSample.sln'.
File name: 'C:\Users\jamlew\Source\Repos\SolutionFilterSample\SolutionFilterSample\SolutionFilterSample.sln'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Construction.SolutionFile.GetSolutionFileAndVisualStudioMajorVersions(String solutionFile, Int32& solutionVersion, Int32& visualStudioMajorVersion)
   at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
```

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET Framework

OS info:
Microsoft Windows [Version 10.0.19041.329]

### PR DESCRIPTION
**Pull request by Forgind**
Solution filter files erroneously combined the current directory with the path from the solution filter file to the solution file. This corrects it to combine the solution filter file's directory with the path from the solution filter file to the solution file and modifies a test to correct that problem.

Fixes #5431.

### CODE REVIEW

File: src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs [hunk 1]
```diff
@@ -155,7 +155,7 @@ public void SolutionFilterFiltersProjects()
                     @"
                 {
                   ""solution"": {
-                    ""path"": """ + solutionFile.Path.Replace("\\", "\\\\") + @""",
+                    ""path"": """ + Path.Combine(".", "SimpleProject", "SimpleProject.sln").Replace("\\", "\\\\") + @""",
```
Comment (rainersigwald) [inline src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:158]: I don't understand this at all. What does this path.combine do?

File: src/Shared/CommunicationsUtilities.cs [hunk 2]
```diff
@@ -336,7 +336,7 @@ internal static long GetHostHandshake(HandshakeOptions nodeType)
             //the most significant byte (leftmost 8 bits) will get zero'd out to avoid connecting to older builds.
             //| masked out | nodeHandshakeSalt | hostContext |              fileVersionHash             | SessionID
             //  0000 0000     0000 0000 0000        0000        0000 0000 0000 0000 0000 0000 0000 0000   0000 0000
-            long baseHandshake = ((long)nodeHandshakeSalt << 44) | ((long)nodeType << 40) | ((long)FileVersionHash << 8);
+            long baseHandshake = (nodeHandshakeSalt << 40) ^ ((long)nodeType << 32) ^ FileVersionHash;
```
Comment (rainersigwald) [inline src/Shared/CommunicationsUtilities.cs:339]: Remove from this PR before merging.

Comment (Forgind) [reply src/Shared/CommunicationsUtilities.cs:339]: I will. I wanted more validation that it worked.

File: src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs (hunk 1 above)
Comment (Forgind) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:158]: The test previously had an absolute path to the solution file. This is making it a relative path. Since the directory is also different from that with the solution filter file, this is essentially testing that MSBuild looks at the directory of the solution filter file in calculating the path to the solution file rather than using the current directory.

Comment (rainersigwald) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:158]: ah. Well, it should definitely have a relative path. Can you _also_ add an assert that the current working directory is not the slnf directory?
