### PR TITLE
ResXFileRef special cases

### LINKED ISSUE #2272: Generating strongly typed resource files not currently supported on .NET Core MSBuild
_From @iSazonov on July 6, 2017 13:41_

What is a right repo to ask about ResGen in `dotnet build`?

Currently I try to generate strongly typed resources and get error:
```C:\Users\user\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview2-006502\Microsoft.Common.CurrentVersion.targets(2921,5): error : Generating strongly typed resource files not currently supported on .NET Core MSBuild [C:\Users\user\Documents\GitHub\iSazonov\PowerShell\src\Microsoft.PowerShell.CoreCLR.Eventing\Microsoft.PowerShell.CoreCLR.Eventing.csproj]```

From related Issue https://github.com/dotnet/cli/issues/819:
> dotnet-resgen  got replaced by the  Microsoft.Net.Sdk  implementation, so closing this.

Is strongly typed resources supported?

_Copied from original issue: dotnet/cli#7084_

### LINKED ISSUE #4581: GenerateResource has incomplete handling for ResXFileRef
Copied from https://github.com/dotnet/corefx/issues/39980, filed by @Symbai

Accessing a resource file throws a `System.MissingMethodException: Constructor on type 'System.Byte[]' not found.`

Please see linked issue for repro.

ResX contains
```xml
  <data name="TestFile" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\Resources\TestFile;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
```

GenerateResource is treating this as an Activator resource and adding it via AddActivatorResource. 
https://github.com/microsoft/msbuild/blob/d31fdbf016616835b237d2846f3f1535560bb2d5/src/Tasks/ResourceHandling/FileStreamResource.cs#L44

Here's the relevant desktop code: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/Resources/ResXFileRef.cs,313
```c#
if(toCreate.Equals(typeof(byte[]))) {
    created = temp;
} else {
    MemoryStream memStream = new MemoryStream(temp);
    if(toCreate.Equals(typeof(MemoryStream))) {
        return memStream;
    } else if(toCreate.Equals(typeof(System.Drawing.Bitmap)) && fileName.EndsWith(".ico")) {
        // we special case the .ico bitmaps because GDI+ destroy the alpha channel component and
        // we don't want that to happen
        Icon ico = new Icon(memStream);
        created = ico.ToBitmap();
    } else {
        created = Activator.CreateInstance(toCreate, BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance, null, new Object[] {memStream}, null);
    }
}
```
It looks like we missed a special case for `byte[]`.  There is also a special case here for `MemoryStream` that is likely also relevant.

### PR DESCRIPTION
**Pull request by rainersigwald**
## Description

Add special cases in build-time resource embedding for the resource types `byte[]` and `MemoryStream`. Fixes #4581.

Enable `StronglyTypedResourceBuilder` when running on .NET Core and ensure that projects built using the .NET Core codepath get code generated using the expected types for resources. Fixes #4588, fixes #2272.

## Customer Impact

Accessing some resources would throw an exception at runtime instead of returning a resource of type `byte[]` or `MemoryStream`.

Projects affected by either problem would have to workaround by:
1. Build using desktop `MSBuild.exe`, not `dotnet build`
2. Explicitly disable the new .NET Core resource-handling codepath in the projects.

## Regression

Regression from .NET Framework functionality; bugs in features new to crossplatform .NET Core MSBuild.

## Risk

Low--impacts only the new resource codepaths.

### CODE REVIEW

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs [hunk 1]
```diff
@@ -234,10 +233,46 @@ private static void AddLinkedResource(string resxFilename, bool pathsRelativeToB
...
+        /// </remarks>
+
+        private static bool IsByteArray(string fileRefType)
+        {
+            return fileRefType.IndexOf("System.Byte[]") != -1 && fileRefType.IndexOf("mscorlib") != -1;
+        }
+
+        private static bool IsMemoryStream(string fileRefType)
+        {
+            return fileRefType.Equals(MemoryStreamTypeNameDesktopFramework, StringComparison.Ordinal) || fileRefType.Equals(MemoryStreamTypeNameCore, StringComparison.Ordinal);
```
Comment (rainersigwald) [inline src/Tasks/ResourceHandling/MSBuildResXReader.cs]: @ericstj Do I need to check both of these, or would just the desktop-framework flavor be sufficient? I wrote a resx using the Core `ResXResourceWriter` and it did embed

```xml
  <data name="ref" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>whatever.txt;System.IO.MemoryStream, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e</value>
  </data>
```

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs [hunk 2]
```diff
@@ -234,10 +233,46 @@ private static void AddLinkedResource(string resxFilename, bool pathsRelativeToB
...
+        /// <remarks>
+        /// We can't hard-code byte[] type name due to version number
+        /// updates & potential whitespace issues with ResX files.
+        ///
+        /// Comment and logic from https://github.com/dotnet/winforms/blob/16b192389b377c647ab3d280130781ab1a9d3385/src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs#L411-L416
+        /// </remarks>
+
+        private static bool IsByteArray(string fileRefType)
+        {
+            return fileRefType.IndexOf("System.Byte[]") != -1 && fileRefType.IndexOf("mscorlib") != -1;
```
Comment (livarcocc) [inline src/Tasks/ResourceHandling/MSBuildResXReader.cs]: NIT: Should you have variables for these strings, like you have on IsMemoryStream?

Comment (rainersigwald) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: For this, I'm preserving the code as it was in the original ResXReader code in the comment above. Would you prefer static strings? I'm not opposed.

**Comment by livarcocc** [comment]
No tests?

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs (hunk 2 above)
Comment (livarcocc) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: Not super worried about it.

**Comment by rainersigwald** [comment]
Testing the types of failures this fixes is difficult at the moment. I filed dotnet/sdk#3549 to create some end-to-end tests in a repo that already has good infrastructure to support building and running test projects.

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs (hunk 1 above)
Comment (nguerrera) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: System.Private.CoreLib should not persist to source files. I think there would need to be some affordance for that when writing a resx, even if it were a resx that only needed to work with core.

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs (hunk 2 above)
Comment (nguerrera) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: (Realize this is preserved, but sure is hacky that this is just a couple of indexofs that would have all sorts of false matches in theory.)

Comment (rainersigwald) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: Yeah, its primary purpose these days is to make everyone who looks at it sad :(

File: src/Tasks/ResourceHandling/MSBuildResXReader.cs (hunk 1 above)
Comment (nguerrera) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: I think it should be using TypeForwardedFromAttribute to write out the original identity. That leads me to believe we do not need to support the core identity. Since nothing is writing core-specfic resx files yet in VS, I think we should wait and see how this shakes out. I would not bake System.Private.CoreLib into our code base unless we are told to do so by corefx.

Comment (rainersigwald) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: Ok, removed `System.Private.CoreLib` from here and #4638.

Comment (ericstj) [reply src/Tasks/ResourceHandling/MSBuildResXReader.cs]: Right, we had requested this ResX designer use TypeForwardedFrom.

**Comment by ManoharRT** [comment]
I have same issue with byte[] on .NetCore3.0. Could someone please help me to fix this?

`System.MissingMethodException: Constructor on type 'System.Byte[]' not found. at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Activator.CreateInstance(Type type, Object[] args) at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex) at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode) at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString) at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase) at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream) at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)`

**Comment by ericstj** [comment]
@ManoharRT please open a new issue with complete repro details.  https://github.com/microsoft/msbuild/issues/new/choose
