### PR TITLE
Calculate a better MSBuild tools/extensions path

### LINKED ISSUE #704: Calculate a better MSBuild tools/extensions path
Need to fix the [FileUtilities](https://github.com/Microsoft/msbuild/blob/master/src/Shared/FileUtilities.cs) class and extract logic to a new class. These are the scenarios I want to consider.

## Tools / Extensions Paths
- When running in MSBuild.exe:
  - Set the Tools Path to current directory (expanded, not using `"."`).
  - Assume we're running in `<Root>\MSBuild\15.0\Bin` and choose `<Root>\MSBuild` for Extensions Path (`ToolsPath\..\..`).
- Running as a dependency and that folder is "complete":
  - Use the reference folder location as the Tools Path.
  - Assume we're running in `<Root>\MSBuild\15.0\Bin` and choose `<Root>\MSBuild` for Extension (`ToolsPath\..\..`).
- Running as a dependency that is not "complete":
  - Discard that folder and try to fallback to a well known location. 
  - For Dev15 (`VisualStudioVersion >= 15'`), this would be `%VSINSTALLDIR%\MSBuild\15.0\Bin` for Tools Path and  `%VSINSTALLDIR%\MSBuild` for Extensions Path.

_Note: By "complete" I mean contains enough of MSBuild to do a build. I will probably check for msbuild.exe and msbuild.exe.config as a minimum bar. This will cover the case that you create an app that references Microsoft.Build.*.dll and it gets copied to your output. Your output should not be considered a tools path unless it contains those files._

### If `%VSINSTALLDIR%` doesn't exist

- We could throw an Exception and tell the user to run from a Visual Studio command prompt.? We no longer have the ability to determine a valid location.
- Use global Visual Studio API to determine a location for Visual Studio (there may be multiple) and pick one of them.

### Running Open Source Build

- We don't want to pick up the Visual Studio Tools Path or Extensions Path in this scenario. Note that Extensions Path would be broken by the above logic because our build layout is like `bin\x86\Windows_NT\Debug\`. The Extensions Path would point to `x86` or something similarly wrong.
- This isn't really solvable without producing a build layout in the right format and pulling in all our run-time dependencies (what the bootstrap proj does now).

This is related to #702 which is a temporary workaround.

### PR DESCRIPTION
**Pull request by AndyGerlicher**
Move all build path environment discovery to new class
 - With Dev15, finding MSBuild is a bit trickier. This change tries to
   address that by moving the logic to a single place and streamlining the
   usage.
 - Audited code that needed to find the MSBuild path to use this.
   Previously there were a variety of methods used, ideally this should be
   the only one (other than perhaps finding tools from another toolset).

Closes #704

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build please

File: src/Shared/BuildEnvironmentHelper.cs [hunk 1]
```diff
@@ -0,0 +1,314 @@
...
+
+        private static string GetCurrentDirectory()
+        {
+            return Directory.GetCurrentDirectory();
+        }
+
+        /// <summary>
+        /// Resets the current singleton instance (for testing).
+        /// </summary>
+        internal static void ResetInstance(Func<string> getProcessFromCommandLine = null, Func<string> getProcessFromRunningProcess = null, Func<string> getExecutingAssmblyPath =  null, Func<string> getCurrentDirectory = null)
```
Comment (cdmihai) [inline src/Shared/BuildEnvironmentHelper.cs]: Is there a convention for marking test only methods? In some other class (I think the whitelisted property functions) I saw the test methods prepended with "_TestOnly"

File: src/Shared/BuildEnvironmentHelper.cs [hunk 2]
```diff
@@ -0,0 +1,314 @@
...
+                }
+            }
+
+            // VSInstallDir is set from the Developer Command Prompt
+            var vsInstallDir = Environment.GetEnvironmentVariable("VSINSTALLDIR");
+            var vsVersion = Environment.GetEnvironmentVariable("VisualStudioVersion");
+
+            if (!string.IsNullOrEmpty(vsInstallDir) &&
+                !string.IsNullOrEmpty(vsVersion) &&
+                vsVersion == "15.0" &&
```
Comment (cdmihai) [inline src/Shared/BuildEnvironmentHelper.cs]: Is this something that's going to have to be updated with each new VS version? If so, can you replace it with something like (Float.Parse(vsVersion) >= 15)?

File: src/Shared/BuildEnvironmentHelper.cs [hunk 3]
```diff
@@ -0,0 +1,314 @@
...
+            bool runningInVisualStudio;
+            var visualStudioPath = FindVisualStudio(
+                new[] {processNameCommandLine, processNameCurrentProcess},
+                out runningInVisualStudio);
+
+            string msbuildFromVisualStudioRoot = null;
+            if (!string.IsNullOrEmpty(visualStudioPath))
+            {
+                msbuildFromVisualStudioRoot =
+                    Path.Combine(Path.Combine(Path.Combine(visualStudioPath, "MSBuild"), "15.0"), "Bin");
```
Comment (cdmihai) [inline src/Shared/BuildEnvironmentHelper.cs]: Same thing for hardcoded 15

File: src/Shared/Strings.shared.resx [hunk 4]
```diff
@@ -247,10 +247,14 @@
     <value>MSB5021: "{0}" and its child processes are being terminated in order to cancel the build.</value>
     <comment>{StrBegin="MSB5021: "}</comment>
   </data>
+  <data name="Shared.CanNotFindValidMSBuildLocation">
+    <value>MSB5024: Could not determine a valid location to MSBuild. Try running this process from the Developer Command Prompt for Visual Studio.</value>
```
Comment (cdmihai) [inline src/Shared/Strings.shared.resx]: This will be a good test for the entire localization pipeline :)

File: src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs [hunk 5]
```diff
@@ -0,0 +1,236 @@
...
+                ["VisualStudioVersion"] = Environment.GetEnvironmentVariable("VisualStudioVersion"),
+            };
+
+            public EmptyBuildEnviroment()
+            {
+                try
+                {
+                    var files = new[] { "msbuild.exe", "msbuild.exe.config" };
+                    TempFolderRoot = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
+                    BuildDirectory = Path.Combine(TempFolderRoot, "MSBuild", "15.0", "Bin");
```
Comment (cdmihai) [inline src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs]: This mock will get interesting if the layout changes in future VS versions :)

**Comment by cdmihai** [comment]
LGTM with minor comments for hardcoded "15.0". Really great to see needless duplication removed! :)

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT Build please
