### PR TITLE
Ensure directory entries in zips are not created

### LINKED ISSUE #3884: Unzip task fails when trying to create directories.
### Steps to reproduce

I have the following project file. During the build step many errors are produced that it can't create files. All the files are laid down correctly and the files that it thinks it can't create are actually directories.

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net46</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
  <Target Name="DownloadContentFiles">
    <DownloadFile
        SourceUrl="https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip"
        DestinationFolder="$(OutputPath)">
      <Output TaskParameter="DownloadedFile" ItemName="Content" />
    </DownloadFile>
  </Target>

  <Target Name="UnzipArchive" BeforeTargets="Build" DependsOnTargets="DownloadContentFiles">
    <Unzip
        SourceFiles="$(OutputPath)\winpty-0.4.3-msvc2015.zip"
        DestinationFolder="$(OutputPath)\unzipped"
        OverwriteReadOnlyFiles="true"
        ContinueOnError="true"
        />
  </Target>
</Project>
```

### Expected  behavior
The build should complete with no errors.

### Actual behavior
I get spammed with errors similar to the following:

```
C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "ia32_xp/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\ia32_xp\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\ia32_xp\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "ia32_xp/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\ia32_xp\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\ia32_xp\lib\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64\lib\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64_xp/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64_xp\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64_xp\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64_xp/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64_xp\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\net46\unzipped\x64_xp\lib\'.
1>Done building project "Pty.Net.csproj".
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "ia32_xp/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\ia32_xp\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\ia32_xp\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "ia32_xp/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\ia32_xp\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\ia32_xp\lib\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64\lib\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64_xp/bin/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64_xp\bin\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64_xp\bin\'.
1>C:\Users\micro\source\repos\Pty.Net\src\Pty.Net\Pty.Net.csproj(17,5): warning MSB3936: Failed to open unzip file "x64_xp/lib/" to "C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64_xp\lib\".  Could not find a part of the path 'C:\Users\micro\source\repos\Pty.Net\bin\Pty.Net\Debug\netstandard2.0\unzipped\x64_xp\lib\'.
```

### Environment data
`msbuild /version` output: 15.8.169.51996

OS info: Windows 10 Version	10.0.17763 Build 17763

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): Visual Studio 15.8

### PR DESCRIPTION
**Pull request by mjcheetham**
Ensure that directory entries in zip archives are not attempted to be created as files. Only file entries (and their parent directories) will be created.

Currently using the `<Unzip/>` task with an archive containing directories will fail trying to `File.Open` on a directory.

```
error : Access to the path '/Users/USER/stuff/internalzipdir/' is denied.

at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
at Microsoft.Build.Tasks.Unzip.Extract(ZipArchive sourceArchive, DirectoryInfo destinationDirectory)
at Microsoft.Build.Tasks.Unzip.Execute()
```

Fixes #3884

### CODE REVIEW

File: src/Tasks/Unzip.cs [hunk 1]
```diff
@@ -131,6 +131,14 @@ private void Extract(ZipArchive sourceArchive, DirectoryInfo destinationDirector
             {
                 FileInfo destinationPath = new FileInfo(Path.Combine(destinationDirectory.FullName, zipArchiveEntry.FullName));
 
+                // Zip archives can have directory entries listed explicitly; we should skip these.
+                // The parent directories of any file entries is created just before file creation.
+                char lastChar = destinationPath.FullName[destinationPath.FullName.Length - 1];
+                if (lastChar == Path.DirectorySeparatorChar || lastChar == Path.AltDirectorySeparatorChar)
```
Comment (cdmihai) [inline src/Tasks/Unzip.cs]: Is there a better way of checking whether the entry is a directory? In linux for example, you could have a file ending in backslash.

**Comment by cdmihai** [comment]
Can you please also add some tests in the [test class](https://github.com/cdmihai/msbuild/blob/0c507a29b6d59340ef5221f66df5d953c1049ba1/src/Tasks.UnitTests/Unzip_Tests.cs#L16)?

**Comment by mjcheetham** [comment]
> Can you please also add some tests in the [test class](https://github.com/cdmihai/msbuild/blob/0c507a29b6d59340ef5221f66df5d953c1049ba1/src/Tasks.UnitTests/Unzip_Tests.cs#L16)?

Sure thing!

File: src/Tasks/Unzip.cs (hunk 1 above)
Comment (rainersigwald) [inline src/Tasks/Unzip.cs]: IIRC, on Linux and macOS, both `DirectorySeparatorChar` and `AltDirectorySeparatorChar` are `/`. If the zip format allows `\`, we should probably explicitly check for both here.

Comment (jeffkl) [reply src/Tasks/Unzip.cs]: This is what the .NET Framework does:

https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFileExtensions.ZipArchiveEntry.Extract.cs#L109

```C#
if (Path.GetFileName(fileDestinationPath).Length == 0)
{
    // If it is a directory:

    if (source.Length != 0)
        throw new IOException(SR.IO_DirectoryNameWithData);

        Directory.CreateDirectory(fileDestinationPath);
}
else
{
    // If it is a file:
    // Create containing directory:
    Directory.CreateDirectory(Path.GetDirectoryName(fileDestinationPath));
    source.ExtractToFile(fileDestinationPath, overwrite: overwrite);
}
```

Comment (mjcheetham) [reply src/Tasks/Unzip.cs]: Replaced check with `Path.GetFileName(destinationPath.FullName).Length == 0` to avoid having to reference directory separator characters directly.

Comment (mjcheetham) [reply src/Tasks/Unzip.cs]: I've replaced the check for 'is directory' with this one `Path.GetFileName(destinationPath.FullName).Length == 0`.

The directory is also now explicitly created as this allows archives containing empty directories to also be extracted fully.

**Comment by mjcheetham** [comment]
> > Can you please also add some tests in the [test class](https://github.com/cdmihai/msbuild/blob/0c507a29b6d59340ef5221f66df5d953c1049ba1/src/Tasks.UnitTests/Unzip_Tests.cs#L16)?
> 
> Sure thing!

@cdmihai, I've added a unit test of extracting an archive with both empty and populated directories.

File: src/Tasks/Unzip.cs [hunk 2]
```diff
@@ -131,6 +131,15 @@ private void Extract(ZipArchive sourceArchive, DirectoryInfo destinationDirector
             {
                 FileInfo destinationPath = new FileInfo(Path.Combine(destinationDirectory.FullName, zipArchiveEntry.FullName));
 
+                // Zip archives can have directory entries listed explicitly.
+                // If this entry is a directory we should create the it and move to the next entry.
```
Comment (rainersigwald) [inline src/Tasks/Unzip.cs]:
```suggestion
                // If this entry is a directory we should create it and move to the next entry.
```

**Comment by rainersigwald** [comment]
not sure why CI is being cranky. Retrying.

**Comment by rainersigwald** [comment]
Checks are mysterious. Everything's passing but an old, stale failure is keeping it red. I'm going to bypass.

Thanks @mjcheetham!

**Comment by hickford** [comment]
@rainersigwald  Would you consider backporting this fix to MSBuild 15?

**Comment by rainersigwald** [comment]
@hickford there's a very high bar to clear there; I don't think we'd do that without some very strong motivation, sorry.
