### PR TITLE
Quote path to MSBuild when using CreateProcess

### LINKED ISSUE #3142: MSBuild /m hangs when the .NET Core SDK is installed to a path with a space
### Steps to reproduce

```
mkdir testsln
cd testsln
dotnet new classlib -o testlib
dotnet new console -o testapp
dotnet new sln
dotnet sln add testlib
dotnet sln add testapp

dotnet restore
```

### Expected  behavior

Doesn't stall for minutes.

### Actual behavior

Does stall for minutes.

### Environment data

```
C:\Users\raines\testsln>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008396
 Commit:    400e670faa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008396\

Host (useful for support):
  Version: 2.1.0-preview2-26325-03
  Commit:  95f1b0b97f

.NET Core SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007480 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008396 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30457 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30457 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26325-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by rainersigwald**
`CreateProcess()` takes an argument that is the program to execute and
another argument that's the entire command line, including the program.

MSBuild parses the full command line to read its arguments.

The combination of these behaviors caused problems when creating MSBuild
worker nodes on Windows via CreateProcess if the path to MSBuild.dll
contains a space. The process gets created fine (the space in
`lpApplicationName` doesn't cause a problem) but the command line is
split in a confusing way, because we think, say, `C:\Program` and
`Files\dotnet\dotnet.exe` are separate arguments.

To avoid this, quote `exeName` when adding it to the command line, just
as we quoted `msbuildLocation`.

Fixes #3142.

### CODE REVIEW

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 1]
```diff
@@ -546,7 +546,7 @@ private int LaunchNode(string msbuildLocation, string commandLineArgs)
                 if (NativeMethodsShared.IsWindows)
                 {
                     // Repeat the executable name in the args to suit CreateProcess
-                    commandLineArgs = exeName + " " + commandLineArgs;
+                    commandLineArgs = "\"" + exeName + "\" " + commandLineArgs;
```
Comment (cdmihai) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: Unit test? :)

**Comment by rainersigwald** [comment]
@dotnet-bot test Windows_NT Build for Full please

https://ci2.dot.net/job/Microsoft_msbuild/job/vs15.7/job/innerloop_Windows_NT_Full_prtest/18/testReport/junit/Microsoft.Build.UnitTests.GetSDKReferenceFiles_Tests/GetSDKReferenceFilesTestFixture/LogReferenceAndRedistConflictBetweenSdksDueToCustomTargetPath/

Should not be related.

**Comment by rainersigwald** [comment]
Test will go in master.

**Comment by rainersigwald** [comment]
(CI was green on this commit before, but retriggered after removing the test commit.)
