### PR TITLE
Log a message when nothing is specified to Error and Warning tasks

### LINKED ISSUE #1350: When Text for message/warning/error are empty it doesn't use an empty line for the message
Expected behavior is to have an empty line shown as the message, warning or error and in the case of warning and error for it to be incremented by 1.  

Repro project.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <PropertyGroup>
      <ReallyImportantMessage></ReallyImportantMessage>
    </PropertyGroup>
    <Message Text="Look no message or warning or error below this line.  But the build still failed..."/>
    <Message Text="$(ReallyImportantMessage)"/>
    <Warning Text="$(ReallyImportantMessage)"/>
    <Error Text="$(ReallyImportantMessage)"/>
  </Target>
</Project>
```

### PR DESCRIPTION
**Pull request by jeffkl**
Logs (No message specified)

Closes #1350 

Sample output
```
Build started 12/5/2016 2:41:07 PM.
Project "C:\Users\jeffkl\Desktop\Stuff\1350.proj" on node 1 (default targets).
C:\Users\jeffkl\Desktop\Stuff\1350.proj(8,5): error : (No message specified)
Done Building Project "C:\Users\jeffkl\Desktop\Stuff\1350.proj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\jeffkl\Desktop\Stuff\1350.proj" (default target) (1) ->
(Build target) ->
  C:\Users\jeffkl\Desktop\Stuff\1350.proj(8,5): error : (No message specified)

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.35
```

### CODE REVIEW

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

**Comment by jeffkl** [comment]
@AndyGerlicher does this look good to you?

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

File: src/XMakeTasks/UnitTests/ErrorWarningMessage_Tests.cs [hunk 1]
```diff
@@ -106,16 +106,17 @@ public void Warning()
         }
 
         /// <summary>
-        /// Empty warning should not log an event
+        /// Empty warning SHOULD log an event
```
Comment (rainersigwald) [inline src/XMakeTasks/UnitTests/ErrorWarningMessage_Tests.cs]: Looks like it's been this way for all time™️ (since Whidbey). I can't see if it was a late-breaking change then or anything.
