### PR TITLE
Fix BinaryLogger not creating directories when it doesn't exist

### LINKED ISSUE #2479: Directory for binary log not created
Start msbuild with binary log enabled:

`msbuild.exe /bl:logs\out.binlog`

If the `logs` folder does not exist, msbuild fails.

This means `/bl` cannot easily replace `/flp:filename=` which does ensure directory exists.

### PR DESCRIPTION
**Pull request by samneirinck**
Fixes #2479

### CODE REVIEW

File: src/Build.UnitTests/BinaryLogger_Tests.cs [hunk 1]
```diff
@@ -64,5 +64,25 @@ public void TestBinaryLoggerRoundtrip()
...
+            string directory = Path.Combine(ObjectModelHelpers.TempProjectDir, Guid.NewGuid().ToString("N"));
+            string log = Path.Combine(directory, "build.binlog");
+            Assert.False(Directory.Exists(directory));
+            Assert.False(File.Exists(log));
+
+            var binaryLogger = new BinaryLogger { Parameters = log };
+
+            try
+            {
+                ObjectModelHelpers.BuildProjectExpectSuccess(s_testProject, binaryLogger);
```
Comment (cdmihai) [inline src/Build.UnitTests/BinaryLogger_Tests.cs]: Maybe repeat the asserts that the directory and file exist

**Comment by KirillOsenkov** [comment]
Wow, thanks for fixing this! 👍
