### PR TITLE
Fix WriteCodeFragment removing duplicate arguments

### LINKED ISSUE #1357: [regression] WriteCodeFragment fails if parameter includes brackets
**Original customer report:** https://github.com/aspnet/Configuration/issues/555

WriteCodeFragment fails if the parameter includes matching brackets.

**Repro**
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Build">
        <ItemGroup>
            <Attr Include="TestAttribute">
                <_Parameter1>Some {value}</_Parameter1>
            </Attr>
        </ItemGroup>
        <WriteCodeFragment Language="C#" AssemblyAttributes="@(Attr)" OutputFile="attr.cs" />
    </Target>
</Project>
```

**Info:**
Using dotnet-CLI 1.0.0-preview3-004056 on Windows 10.
Doesn't repo MSBuild 14.0.

**Stack trace:**
```
  "C:\tmp\test.proj" (default target) (1) ->
       (Build target) ->
         C:\tmp\test.proj(8,9): error MSB4018: The "WriteCodeFragment" task failed unexpectedly.\r
       C:\tmp\test.proj(8,9): error MSB4018: System.FormatException: Input string was not in a correct format.\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.String.Format(String format, Object[] args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.GenerateCodeCoreClr(String& extension)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.Execute()\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

### LINKED ISSUE #3973: WriteCodeFragment skips positional parameters with the same value
### Steps to reproduce

Project file `same_positional_params_test.msbuild`
```xml
<Project>
  <ItemGroup>
    <AssemblyAttribute Include="MyProject.MySpecial">
      <_Parameter1>abc</_Parameter1>
      <_Parameter2>abc</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <Target Name="Build">
    <WriteCodeFragment Language="C#" OutputFile="MyAssemblyInfo.cs" AssemblyAttributes="@(AssemblyAttribute)" />
  </Target>
</Project>
```

Command line (powershell or cygwin bash)
```
$ dotnet msbuild /bl same_positional_params_test.msbuild
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.1.500\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\2.1.500\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\2.1.500\dotnet.dll -maxcpucount -verbosity:m /bl .\same_positional_params.msbuild
$
$ cat .\MyAssemblyInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the MSBuild WriteCodeFragment class.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: MyProject.MySpecial("abc")]
```
### Expected behavior
The resulting `MyAssemblyInfo.cs` file should contain two parameters, corresponding to the two supplied in the msbuild file:
```
[assembly: MyProject.MySpecial("abc", "abc")]
```
### Actual behavior
The second parameter is unexpectedly removed.
```
[assembly: MyProject.MySpecial("abc")]
```
Note that if one of the parameters is changed to "abc2" (i.e. their values are different), then it works again.

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856
```
OS info: `Windows 10 Pro 1803 17134.407`

Invoked with dotnet (as shown above):
```
$ dotnet --version
2.1.500
```

### PR DESCRIPTION
**Pull request by dasMulli**
Fixes #3973

### CODE REVIEW

File: src/Tasks.UnitTests/WriteCodeFragment_Tests.cs [hunk 1]
```diff
@@ -426,6 +426,30 @@ public void OneAttributeTwoPositionalParams()
             File.Delete(task.OutputFile.ItemSpec);
         }
 
+        [Fact]
+        public void OneAttributeTwoSamePositionalParams()
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/WriteCodeFragment_Tests.cs]:
```suggestion
        public void OneAttributeTwoPositionalParamsWithSameValue()
```

?

Comment (dasMulli) [reply src/Tasks.UnitTests/WriteCodeFragment_Tests.cs]: naming things 😢  I'll think of a better one.
