### PR TITLE
Fix TaskParser probably has a bug in switch de-duplication logic.

### LINKED ISSUE #75: TaskParser probably has a bug in switch de-duplication logic.
this class operates with two collections:
_switchesAdded
_switchOrderList

In ParseParameter method _switchesAdded map is used under condition. I think the intent was to filter duplicates in _switchOrderList list but _switchesAdded map is never updated.

### PR DESCRIPTION
**Pull request by szaliszali**
Closes #75 

As far as I could observe, the only way to properly handle duplicate names is to die, because duplicate property names break code generation (code generator creates two fields with the same name), so I added the missing check and a new error message for this case.

### CODE REVIEW

File: src/Tasks.UnitTests/XamlTaskFactory_Tests.cs [hunk 1]
```diff
@@ -191,6 +191,30 @@ public void TestBasicReversibleBooleanSwitches()
...
+                                   </ProjectSchemaDefinitions>";
+                TaskParser tp = XamlTestHelpers.LoadAndParse(incorrectXmlContents, "CL");
+            }
+            catch (XamlParseException ex)
+            {
+                exceptionCaught = true;
+                Assert.Equal("MSB3724: Unable to create Xaml task.  Duplicate property name 'SameName'.", ex.Message);
+            }
+
+            Assert.True(exceptionCaught); // "Should have caught a XamlParseException"
```
Comment (BenVillalobos) [inline src/Tasks.UnitTests/XamlTaskFactory_Tests.cs]: We're trying to use Shouldly where we can (for debugging purposes).
```suggestion
            exceptionCaught.ShouldBeTrue(); // "Should have caught a XamlParseException"
```

File: src/Tasks.UnitTests/XamlTaskFactory_Tests.cs [hunk 2]
```diff
@@ -191,6 +191,30 @@ public void TestBasicReversibleBooleanSwitches()
...
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                     </Rule>
+                                   </ProjectSchemaDefinitions>";
+                TaskParser tp = XamlTestHelpers.LoadAndParse(incorrectXmlContents, "CL");
+            }
+            catch (XamlParseException ex)
+            {
+                exceptionCaught = true;
+                Assert.Equal("MSB3724: Unable to create Xaml task.  Duplicate property name 'SameName'.", ex.Message);
```
Comment (BenVillalobos) [inline src/Tasks.UnitTests/XamlTaskFactory_Tests.cs]:
```suggestion
                ex.Message.ShouldBe("MSB3724: Unable to create Xaml task.  Duplicate property name 'SameName'.");
```

File: src/Tasks/XamlTaskFactory/TaskParser.cs [hunk 3]
```diff
@@ -307,8 +307,13 @@ private bool ParseParameter(XamlTypes.BaseProperty baseProperty, LinkedList<Prop
             // generate the list of parameters in order
             if (!_switchesAdded.Contains(propertyToAdd.Name))
             {
+                _switchesAdded.Add(propertyToAdd.Name);
```
Comment (Forgind) [inline src/Tasks/XamlTaskFactory/TaskParser.cs]: It looks like `_switchesAdded` wasn't used previously, and `_switchOrderList` was used only as an enumerable. Since Contains is noticeably faster for a set than for a list, perhaps replace all uses of _switchOrderList with _switchesAdded?

Comment (szaliszali) [reply src/Tasks/XamlTaskFactory/TaskParser.cs]: no, original ordering of `_switchOrderList` is used after parsing the task, line 599 of the `CommandLineGenerator` class (`foreach (string propertyName in _switchOrderList)`)

however, the opposite may be true, because, the typical property count of a task is in the range of ~1..10, and linear search outperforms hashset for very small item counts and task parsing is not executed very often during a build, so we could eliminate the _switchesAdded variable if we would really want to eliminate one of them

Comment (Forgind) [reply src/Tasks/XamlTaskFactory/TaskParser.cs]: I saw that, but I didn't think order really mattered for that loop—command lines shouldn't care about the order in which switches are presented—but upon reflection, that might break someone's tests.

I commented to @BenVillalobos that I'd like it better as a TreeSet, which would beat both versions on (almost) any normal-sized input as far as time. (Also assuming nodes aren't too far apart in memory.) I would be slightly worried by the "typical" part without asking Rainer's opinion, but I think I'd be content with how you originally had it or how it is now. Approved, pending @rainersigwald's approval.

Comment (szaliszali) [reply src/Tasks/XamlTaskFactory/TaskParser.cs]: I agree that the order of options can be _usually_ discarded, but there are many edge cases where the order becomes important: for example, CL documentation says: "If CL encounters conflicting options, it uses the rightmost option." (https://docs.microsoft.com/en-us/cpp/build/reference/order-of-cl-options?view=vs-2019), also it is general practice in the unix world that everything after a `--` won't be handled as an option but a filename, so if you would reorder that then you would get a lot of file not found errors when the program tries to load the switch as a file

File: src/Tasks.UnitTests/XamlTaskFactory_Tests.cs [hunk 4]
```diff
@@ -191,6 +191,30 @@ public void TestBasicReversibleBooleanSwitches()
...
+            {
+                string incorrectXmlContents = @"<ProjectSchemaDefinitions xmlns=`clr-namespace:Microsoft.Build.Framework.XamlTypes;assembly=Microsoft.Build.Framework` xmlns:x=`http://schemas.microsoft.com/winfx/2006/xaml` xmlns:sys=`clr-namespace:System;assembly=mscorlib` xmlns:impl=`clr-namespace:Microsoft.VisualStudio.Project.Contracts.Implementation;assembly=Microsoft.VisualStudio.Project.Contracts.Implementation`>
+                                     <Rule Name=`CL`>
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                     </Rule>
+                                   </ProjectSchemaDefinitions>";
+                TaskParser tp = XamlTestHelpers.LoadAndParse(incorrectXmlContents, "CL");
+            }
+            catch (XamlParseException ex)
```
[the remark this answers is not in the document]
Comment (BenVillalobos) [reply src/Tasks.UnitTests/XamlTaskFactory_Tests.cs]: Note the `ShouldStartWith("MSB3724")` is actually a better check because it also works with localized strings.

File: src/Tasks/XamlTaskFactory/TaskParser.cs (hunk 3 above)
Comment (rainersigwald) [reply src/Tasks/XamlTaskFactory/TaskParser.cs]: I agree that we should preserve order, and that the N here should be low enough that the lookup being N^2 shouldn't be a big problem.

But let's double check that against VS perf tests. @Forgind can you push this to an exp/ branch and see if RPS is green?

File: src/Tasks.UnitTests/XamlTaskFactory_Tests.cs [hunk 5]
```diff
@@ -191,6 +192,25 @@ public void TestBasicReversibleBooleanSwitches()
...
+                                       xmlns:impl=`clr-namespace:Microsoft.VisualStudio.Project.Contracts.Implementation;assembly=Microsoft.VisualStudio.Project.Contracts.Implementation`>
+                                     <Rule Name=`CL`>
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                       <BoolProperty Name=`SameName` Switch=`Og` ReverseSwitch=`Og-` />
+                                     </Rule>
+                                   </ProjectSchemaDefinitions>";
+
+            Should
+                .Throw<XamlParseException>(() => XamlTestHelpers.LoadAndParse(incorrectXmlContents, "CL"))
+                .Message.ShouldBe("MSB3724: Unable to create Xaml task.  Duplicate property name 'SameName'.");
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/XamlTaskFactory_Tests.cs]: See https://github.com/microsoft/msbuild/pull/5115#discussion_r378399416 please

**Comment by BenVillalobos** [comment]
/azp run

Not sure why the build is suddenly failing

**Comment by Forgind** [comment]
[RPS in progress](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/228714?_a=overview)
