### PR TITLE
Exec task unicode fix

### LINKED ISSUE #142: Exec task fails with Unicode characters
Run Exec task with non-ANSI characters in the command:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Build">
        <Exec Command="创建\test.cmd"/>
    </Target>
</Project>
```

This doesn't work. Exec creates a temp cmd file and executes it.

Cmd file looks like:
```
setlocal
set errorlevel=dummy
set errorlevel=
??\test.cmd
exit %errorlevel%
```
This was done on purpose a very long time ago (Windows XP doesn't support this scenario).

### PR DESCRIPTION
**Pull request by AndyGerlicher**
Fixes #142 and probably #104 (thanks @akoeplinger for pointing that out!).

Definitely not an expect on code pages and cmd.exe encoding, but this works better than previously in all the scenarios I tested. 

The only remaining encoding issue I found is if the command you run has non-ansi characters (e.g. `echo 创建` was the test case I used), it will still show up as ?? on the console. I don't think that can be fixed here though.

### CODE REVIEW

**Comment by rainersigwald** [comment]
LGTM.

File: src/XMakeTasks/Exec.cs [hunk 1]
```diff
@@ -299,6 +217,13 @@ private void CreateTemporaryBatchFile()
                 sw.WriteLine("set errorlevel=dummy");
                 sw.WriteLine("set errorlevel=");
 
+                // We probably have to change the code page to UTF8 (65001) for non-ansi characters to work.
+                if (EncodingUtilities.CurrentSystemOemEncoding.CodePage != sw.Encoding.CodePage)
+                {
+                    // Output to nul so we don't change output and logs.
+                    sw.WriteLine($"chcp {sw.Encoding.CodePage}>nul");
```
Comment (akoeplinger) [inline src/XMakeTasks/Exec.cs]: You're using C#6 features here, is the solution already updated to that?

File: src/XMakeTasks/Exec.cs [hunk 2]
```diff
@@ -33,71 +28,43 @@ public class Exec : ToolTaskExtension
         /// </summary>
         public Exec()
         {
-            // do nothing
+            Command = string.Empty;
+
+            // Console-based output uses the current system OEM code page by default. Note that we should not use Console.OutputEncoding
+            // here since processes we run don't really have much to do with our console window (and also Console.OutputEncoding
+            // doesn't return the OEM code page if the running application that hosts MSBuild is not a console application).
+            // Note: 8/12/15 - Changed encoding to use UTF8 when OS is newer than 6.1 (Windows 7)
```
Comment (akoeplinger) [inline src/XMakeTasks/Exec.cs]: >  newer than 6.1 (Windows 7)

It's actually newer **or equal** based on the code

File: src/XMakeTasks/Exec.cs [hunk 3]
```diff
@@ -645,5 +557,23 @@ protected override MessageImportance StandardOutputLoggingImportance
         }
 
         #endregion
+
+        private static readonly Encoding s_utf8WithoutBom = new UTF8Encoding(false);
+
+        /// <summary>
+        /// Get encoding based on OS. This will fall back to previous behavior on any OS before Windows 7.
+        /// If the OS is greater than Windows 7, UTF8 encoding will be used for the cmd file.
```
Comment (akoeplinger) [inline src/XMakeTasks/Exec.cs]: > greater than Windows 7

greater **or equal**

**Comment by akoeplinger** [comment]
Left some comments, LGTM otherwise (though I'd preferred if the reformatting of the properties etc. were done in a separate commit, so the real change is easier to see).

File: src/XMakeTasks/Exec.cs (hunk 1 above)
Comment (AndyGerlicher) [inline src/XMakeTasks/Exec.cs]: Good point, probably best to just not go there at this point. Especially for a single change and I'm not sure what it would do to the xplat / Xamarin Studio story when this gets merged.
