### PR TITLE
Fix issue importing an SDK via Import element.

### LINKED ISSUE #2034: Sdk imports broken in latest build.
Install D15PreRel 26427.3
Create a project like this:

```xml
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
</Project>
```

msbuild fails with:
```
C:\Users\srivatsn\Documents\Visual Studio 2017\Projects\ClassLibrary9\ClassLibrary9\ClassLibrary9.csproj" (default tar
get) (1) ->
  C:\Users\srivatsn\Documents\Visual Studio 2017\Projects\ClassLibrary9\ClassLibrary9\ClassLibrary9.csproj(3,3): error
MSB4019: The imported project "C:\Users\srivatsn\Documents\Visual Studio 2017\Projects\ClassLibrary9\ClassLibrary9\Sdk.
props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

### PR DESCRIPTION
**Pull request by AndyGerlicher**
* This feature was regressed in #2002
* Update unit tests to verify functionality
* Update ProjectParser to parse SDK name/version values and construct an SdkReference object to be used by the evaluator.

Closes #2034

### CODE REVIEW

**Comment by jeffkl** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR please

File: src/Build/Evaluation/ProjectParser.cs [hunk 1]
```diff
@@ -515,12 +516,19 @@ private ProjectImportElement ParseProjectImportElement(XmlElementWithLocation el
...
-
             ProjectXmlUtilities.VerifyThrowProjectNoChildElements(element);
 
-            return new ProjectImportElement(element, parent, _project);
+            SdkReference sdk = null;
+            if (element.HasAttribute(XMakeAttributes.sdk))
+            {
+                sdk = new SdkReference(
+                    ProjectXmlUtilities.GetAttributeValue(element, XMakeAttributes.sdk, nullIfNotExists: true),
+                    ProjectXmlUtilities.GetAttributeValue(element, XMakeAttributes.sdkVersion, nullIfNotExists: true),
```
Comment (cdmihai) [inline src/Build/Evaluation/ProjectParser.cs]: So explicit attributes instead of fancy string that needs to be parsed?

The XSD should probably be updated at some point, since SDKs introduced a couple of new attributes / elements.

File: src/Build/Construction/ProjectImportElement.cs [hunk 2]
```diff
@@ -75,13 +76,41 @@ public string Sdk
...
+                if (!CheckUpdatedSdk()) return;
                 ProjectXmlUtilities.SetOrRemoveAttribute(XmlElement, XMakeAttributes.sdk, value);
                 MarkDirty("Set Import Sdk {0}", value);
             }
         }
 
         /// <summary>
+        /// Gets or sets the version associated with this SDK import
+        /// </summary>
+        public string Version
```
Comment (cdmihai) [inline src/Build/Construction/ProjectImportElement.cs]: Add a new test to [construction editing tests](https://github.com/Microsoft/msbuild/blob/master/src/Build.OM.UnitTests/Construction/ConstructionEditing_Tests.cs) to assert null values, non-null values, etc. For example, what happens if you add an SDK import element inside an import group group together with non SDK import elements.

File: src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs [hunk 3]
```diff
@@ -200,32 +196,28 @@ public void ProjectWithSdkImportsIsCloneable(string projectFileFirstLineFormat)
 
   <ItemGroup>
     <PackageReference Include=""Microsoft.NETCore.App"" Version=""1.0.1"" />
-  </ItemGroup>
-
-</Project>";
+  </ItemGroup>";
+            File.WriteAllText(_sdkPropsPath, " < Project />");
```
Comment (rainersigwald) [inline src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs]: Why the spaces?

File: src/Build/Evaluation/ProjectParser.cs (hunk 1 above)
Comment (rainersigwald) [inline src/Build/Evaluation/ProjectParser.cs]: 👍 on xsd update

File: src/Build/Construction/ProjectImportElement.cs [hunk 4]
```diff
@@ -139,5 +168,22 @@ protected override ProjectElement CreateNewInstance(ProjectRootElement owner)
         {
             return owner.CreateImportElement(this.Project);
         }
+
+        private bool CheckUpdatedSdk()
```
Comment (rainersigwald) [inline src/Build/Construction/ProjectImportElement.cs]: Not sure I understand the motivation for this. Can you elaborate?
