### PR TITLE
Fix AssemblyInformation.GetRuntimeVersion on Nano Server

### LINKED ISSUE #1233: MSB1025: An internal failure occurred while running MSBuild on Nano Server
Copied from https://github.com/dotnet/cli/issues/4469
## Steps to reproduce

Build the following Windows Container Dockerfile via `docker build -t preview3 .`

```
FROM microsoft/nanoserver:10.0.14393.321

# Install .NET Core SDK
ENV DOTNET_SDK_VERSION 1.0.0-preview3-003892
ENV DOTNET_SDK_DOWNLOAD_URL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-dev-win-x64.$DOTNET_SDK_VERSION.zip

RUN powershell -NoProfile -Command \
        $ErrorActionPreference = 'Stop'; \
        Invoke-WebRequest %DOTNET_SDK_DOWNLOAD_URL% -OutFile dotnet.zip; \
        Expand-Archive dotnet.zip -DestinationPath '%ProgramFiles%\dotnet'; \
        Remove-Item -Force dotnet.zip

RUN setx /M PATH "%PATH%;%ProgramFiles%\dotnet"

# Trigger the population of the local package cache
ENV NUGET_XMLDOC_MODE skip
RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rmdir /q/s warmup
```
## Expected  behavior

Dockerfile builds without issues.
## Actual behavior

Dockfile fails to build

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.EntryPointNotFoundException: Unable to find an entry point named 'RtlMoveMemory' in DLL 'kernel32.dll'.
   at Microsoft.Build.Internal.CommunicationsUtilities.CopyMemory(Char* destination, Char* source, UInt32 length)
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray()
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'RtlMoveMemory' in DLL 'kernel32.dll'.
   at Microsoft.Build.Internal.CommunicationsUtilities.CopyMemory(Char* destination, Char* source, UInt32 length)
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentCharArray()
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties()
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
Failed to create prime the NuGet cache. restore3 failed with: 255
```
## Environment data

I am using a WS16 environment with the latest updates.

This issue was caught by the dotnet-docker-nightly repo's CI which automatically picks up the latest CLI builds
[PR to uptake 003892](https://github.com/dotnet/dotnet-docker-nightly/pull/78)
[CI failure](https://ci.dot.net/job/dotnet_dotnet-docker-nightly/job/master/job/NanoServer_prtest/10/console)

### PR DESCRIPTION
**Pull request by qmfrederik**
`AssemblyInformation.GetRuntimeVersion` calls into `mscoree.dll`, which is part of NetFX and not available on .NET Core.

Because .NET Core is the only flavour of .NET available on Nano Server, this task would fail on Nano Server.

In this PR, the call to `mscoree.dll` is put behind a `FEATURE_MSCOREE` feature flag which is set for NetFX only. If this feature flag is not set, `ManagedRuntimeVersionReader.GetRuntimeVersion(path);` is used instead.

Related issues:
Closes #1233
dotnet/cli#4469
dotnet/cli#5081

/cc @rainersigwald, @jeffkl

### CODE REVIEW

**Comment by jeffkl** [comment]
Looks good.  Do you happen to have an easy way to test this on Nano to see if MSBuild now succeeds or if it hits another problem?

**Comment by qmfrederik** [comment]
I tested it on Nano Server. `dotnet build` and `dotnet publish` both succeed without errors.

**Comment by jeffkl** [comment]
Awesome!

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Desktop please

File: src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs [hunk 1]
```diff
@@ -489,6 +490,9 @@ internal static string GetRuntimeVersion(string path)
             {
                 return ManagedRuntimeVersionReader.GetRuntimeVersion(path);
             }
+#else
+                return ManagedRuntimeVersionReader.GetRuntimeVersion(path);
```
Comment (jeffkl) [inline src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs]: I haven't seen this code before so I'm hesitant to touch it right now.  Maybe @AndyGerlicher knows if its safe to remove that code?

**Comment by qmfrederik** [comment]
@jeffkl To get this fixed in the .NET CLI repository, I guess we need an updated version of the MSBuild NuGet packages on MyGet. I've noticed the packages on https://dotnet.myget.org/gallery/msbuild are about two weeks old.

Do you push packages to MyGet on a specific schedule?

Thanks!

**Comment by cdmihai** [comment]
@qmfrederik I've triggered a new internal build. New packages should be up today.

**Comment by qmfrederik** [comment]
@cdmihai The updated packages are on MyGet, thanks!
