### PR TITLE
Restore write-resource-to-text tests

### LINKED ISSUE #308: GenerateResource does not fail when converting binary .resx resources to .txt resources
On the full framework, if a .resx data element points to a path and there's a type specified to read that file, the conversion of the .resx resource to a .txt resource is impossible and the tasks logs an error (since .txt resources cannot have binary values).

However, the .net core behaviour is to write the file path to the .txt.

This happens because the full framework uses a special xml reader, ResXResourceReader , that reads a path in the .resx file directly to its specified .net object. However this special xml reader is not available in .net core, so a normal xml reader is used instead, which just reads the text file name.

Tests that capture failure:
- GenerateResource_Tests.UnsupportedTextType, InvalidReference, FailedResourceReader

Other implications
- .resx binary resources with specified .net types don't work.

@dsplaisted Should we copy the ResXResourceReader type to the msbuild codebase? If we try to mimic its behaviour, we end up re-implementing it.

### PR DESCRIPTION
**Pull request by rainersigwald**
Closes #308 by re-enabling the tests.

### CODE REVIEW

**Comment by rainersigwald** [comment]
I thought this worked on my machine but I was testing desktop framework. Sigh. Pulling for now.

File: src/Tasks/GenerateResource.cs [hunk 1]
```diff
@@ -2988,7 +2994,7 @@ private void ReadResources(String filename, bool shouldUseSourcePath, String out
 #if FEATURE_ASSEMBLY_LOADFROM
                 ReadAssemblyResources(filename, outFileOrDir);
 #else
-                _logger.LogError("Reading resources from Assembly not supported on .NET Core MSBuild");
+                throw new InputFormatNotSupportedException("Reading resources from Assembly not supported on .NET Core MSBuild");
```
Comment (Forgind) [inline src/Tasks/GenerateResource.cs]: Why is it advantageous to throw instead of just logging an error? Are you trying to reduce duplicate output?

File: src/Tasks/GenerateResource.cs [hunk 2]
```diff
@@ -3387,8 +3393,13 @@ private bool HaveSystemResourcesExtensionsReference
 
                 PopulateAssemblyNames();
 
-                foreach (var assemblyName in _assemblyNames)
+                foreach (AssemblyNameExtension assemblyName in _assemblyNames)
                 {
+                    if (assemblyName == null)
```
Comment (Forgind) [inline src/Tasks/GenerateResource.cs]: Why would they be null?

File: src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs [hunk 3]
```diff
@@ -0,0 +1,28 @@
+﻿// Copyright (c) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE file in the project root for full license information.
+
+using System;
+using System.Runtime.Serialization;
+
+namespace Microsoft.Build.Tasks.ResourceHandling
+{
+    [Serializable]
+    internal class InputFormatNotSupportedException : Exception
```
Comment (Forgind) [inline src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs]: Is there a reason you can't use `FormatException` or `ArgumentException` instead of making your own (empty) new type of exception?

File: src/Tasks/Resources/xlf/Strings.es.xlf [hunk 4]
```diff
@@ -979,6 +979,11 @@
         <target state="translated">MSB3190: ClickOnce no admite el nivel de ejecución de solicitudes '{0}'.</target>
         <note>{StrBegin="MSB3190: "}</note>
       </trans-unit>
+      <trans-unit id="GenerateResource.CoreSupportsLimitedScenarios">
+        <source>MSB3824: In order to build with .NET Core, resource inputs must be in .txt or .resx format.</source>
```
Comment (Forgind) [inline src/Tasks/Resources/xlf/Strings.es.xlf]: I'm guessing this is supposed to be a localized version. When does that happen?

Comment (rainersigwald) [reply src/Tasks/Resources/xlf/Strings.es.xlf]: Correct.  The loc team periodically (at least once per minor release) does a pass on strings and will submit a PR with updated localizations (#4679 was a recent one). Until that's done the English copy of the string is used.

Docs are here: https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Localization.md

File: src/Tasks/GenerateResource.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Tasks/GenerateResource.cs]: Logging an error here is nonfatal, so the experience with going through this codepath was:

1. This error.
2. Some other odd output when trying to move on.
3. Another fatal error that didn't directly indicate the problem.

Since there were already exception-based error paths in `ProcessFile` I opted to add another rather than change everything to error returns.

File: src/Tasks/GenerateResource.cs (hunk 2 above)
Comment (rainersigwald) [reply src/Tasks/GenerateResource.cs]: That's what happens if an assembly name can't be extracted from a reference for some reason in `PopulateAssemblyNames()`. The other codepaths were robust to this situation but this newly-added one wasn't (until running a test revealed the error).

File: src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs (hunk 3 above)
Comment (rainersigwald) [reply src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs]: Having a custom exception type makes detecting this error condition easy using a catch-specific-type block.

Comment (Forgind) [reply src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs]: Tracing how it's currently caught, I believe a FormatException will still have the exact same effect.

Also, I don't see anywhere that you try to catch it; do you have plans for adding something like that in the future? If not, you're breaking something that could otherwise be caught by an ArgumentException, failing more cleanly.

Comment (rainersigwald) [reply src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs]: > I believe a FormatException will still have the exact same effect.

Since it's a standard exception type, other code could insert a `FormatException` that would then be inadvertently caught and handled as this specific problem, rather than handled at another layer.

> Also, I don't see anywhere that you try to catch it

https://github.com/microsoft/msbuild/pull/4830/files#diff-1d2aacce8c88cda3235c1659ea67e164R2606-R2611

> If not, you're breaking something that could otherwise be caught by an ArgumentException, failing more cleanly.

This is harder to distinguish since other places could throw `ArgumentException` inside the big `ProcessFile` catch block.

File: src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs [hunk 5]
```diff
@@ -3711,16 +3724,27 @@ public static string WriteTestResX(bool useType, string linkedBitmap, string ext
...
-            if (string.IsNullOrEmpty(resgenFile))
+
+            string contents = GetTestResXContent(useType, linkedBitmap, extraToken, useInvalidType);
+
+            if (env == null)
+            {
+                if (string.IsNullOrEmpty(resgenFile))
+                {
+                        resgenFile = GetTempFileName(".resx");
+                        File.Delete(resgenFile);
```
Comment (BenVillalobos) [inline src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs]: (nit) Is this line necessary? According to the [File.WriteAllText documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=netframework-4.8), even if the file did exist it would be overwritten

Comment (rainersigwald) [reply src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs]: It's preexisting but no, I don't think it is. I'll remove.
