### PR TITLE
Exclude computation skips over illegal file specs

### LINKED ISSUE #1523: **.* exclude pattern throws exception
The following project
```xml
<Project>
    <ItemGroup>
       <i Include="**\*" Exclude="**.*"/>
    </ItemGroup>

    <Target Name="Build">
        <Message Text="[@(i)]" Importance="high"/>
    </Target>
</Project>
```

Throws an exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.FileUtilities.ToSlash(String s) in d:\projects\msbuild_2\src\Shared\FileUtilities.cs:line 1016
   at Microsoft.Build.Shared.FileUtilities.NormalizeForPathComparison(String s) in d:\projects\msbuild_2\src\Shared\FileUtilities.cs:line 1019
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped, GetFileSystemEntries getFileS
ystemEntries, DirectoryExists directoryExists) in d:\projects\msbuild_2\src\Shared\FileMatcher.cs:line 1584
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped) in d:\projects\msbuild_2\src\
Shared\FileMatcher.cs:line 1351
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileList(String directoryEscaped, String filespecEscaped, Boolean returnEscaped, IEnumerable`1 excludeSpecsEscaped) in d:\
projects\msbuild_2\src\XMakeBuildEngine\Utilities\EngineFileUtilities.cs:line 131
   at Microsoft.Build.Internal.EngineFileUtilities.GetFileListEscaped(String directoryEscaped, String filespecEscaped, IEnumerable`1 excludeSpecsEscaped) in d:\projects\msbuild
_2\src\XMakeBuildEngine\Utilities\EngineFileUtilities.cs:line 60
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.IncludeOperation.SelectItems(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in d:\projects\msbuild_2\src\XMakeBuild
Engine\Evaluation\LazyItemEvaluator.IncludeOperation.cs:line 103
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in d:\projects\msbuild_2\src\XMakeBuildEngin
e\Evaluation\LazyItemEvaluator.LazyItemOperation.cs:line 47
```

MSBuild 14 ignores the `**.*` exclude (actually, it treats it as a literal string, and on windows no files can match it, and therefore it behaves like it's ignored)

### PR DESCRIPTION
**Pull request by cdmihai**
Resolves #1523

### CODE REVIEW

File: src/Shared/FileMatcher.cs [hunk 1]
```diff
@@ -1475,18 +1475,21 @@ static string[] CreateArrayWithSingleItemIfNotExcluded(string filespecUnescaped,
             {
                 foreach (string excludeSpec in excludeSpecsUnescaped)
                 {
-                    //  The FileMatch method always creates a Regex to check if the file matches the pattern
-                    //  Creating a Regex is relatively expensive, so we may want to avoid doing so if possible
-                    Result match = FileMatch(excludeSpec, filespecUnescaped);
+
+                    if (FileUtilities.PathsEqual(filespecUnescaped, excludeSpec))
```
Comment (AndyGerlicher) [inline src/Shared/FileMatcher.cs]: This block seems worthy of a comment explaining. Agreed with deleting the old comment since it was decent advice that was promptly not followed :)
