### PR TITLE
Prevent duplicate targets Fixes #5071

### LINKED ISSUE #5071: Defining Build target in before.Solution.sln.targets causes hang, MSB0001
Hi,
Sorry this is going to be vague, but I wanted to log it with you anyway.
Msbuild is hanging when I invoke directly on our solution. Works fine in 16.3.X, but hangs/fails on 16.4.X.
When pushing Ctrl+c to cancel the build I get the error at the bottom of the post.

### Steps to reproduce
Unfortunately I cannot attach a sample as it is of our proprietary software. 
Our solution is about 70 projects, with a mix of C#, C++ and C++/CLR.
I have included the import config from Visual Studio.
[2019.vsconfig.txt](https://github.com/microsoft/msbuild/files/4108358/2019.vsconfig.txt)

### Environment data

Invoking MSBuild Directly:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin>msbuild "C:\pathto\OurSolution.sln"
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 24/01/2020 11:51:10.
Attempting to cancel the build...

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:45.57 (edit: this is an example, I have waited hours and nothing appears on the commandline)
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Target Build already exists.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.ProjectInstance.AddTarget(String targetName, String condition, String inputs, String outputs, String returns, String keepDuplicateOutputs, String dependsOnTargets, String beforeTargets, String afterTargets, Boolean parentProjectSupportsReturnsAttribute)
   at Microsoft.Build.Construction.SolutionProjectGenerator.AddTraversalReferencesTarget(ProjectInstance traversalProject, String targetName, String outputItem)
   at Microsoft.Build.Construction.SolutionProjectGenerator.AddStandardTraversalTargets(ProjectInstance traversalInstance, List`1 projectsInOrder)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
   at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
   at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass70_0.<ExecuteSubmission>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Target Build already exists.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Target Build already exists.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### PR DESCRIPTION
**Pull request by Forgind**
Duplicate targets break the build; this prevents MSBuild's default targets from being added if they already exist.

Fixes #5071

### CODE REVIEW

File: src/Build/Construction/Solution/SolutionProjectGenerator.cs [hunk 1]
```diff
@@ -1969,8 +1969,11 @@ private static void AddTraversalReferencesTarget(ProjectInstance traversalProjec
                 outputItemAsItem = "@(" + outputItem + ")";
             }
 
-            ProjectTargetInstance target = traversalProject.AddTarget(targetName ?? "Build", String.Empty, String.Empty, outputItemAsItem, null, String.Empty, String.Empty, String.Empty, String.Empty, false /* legacy target returns behaviour */);
-            AddReferencesBuildTask(target, targetName, outputItem);
+            if (!traversalProject.Targets.Select(target => target.Key).Contains(targetName ?? "Build"))
+            {
+                ProjectTargetInstance target = traversalProject.AddTarget(targetName ?? "Build", string.Empty, string.Empty, outputItemAsItem, null, string.Empty, string.Empty, string.Empty, string.Empty, false /* legacy target returns behaviour */);
```
Comment (jeffkl) [inline src/Build/Construction/Solution/SolutionProjectGenerator.cs]: This fix looks right, but can you add a unit test that proves it does what we think?

File: src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs [hunk 2]
```diff
@@ -60,6 +60,35 @@ public void Dispose()
...
+                TransientTestFile targetsFile = testEnvironment.CreateFile(folder, name,
+                    @"<Project ToolsVersion=""15.0"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
+                        <Target Name=""Build"" AfterTargets=""NonsenseTarget"">
+                        </Target>
+                      </Project>");
+                ProjectInstance[] instances = SolutionProjectGenerator.Generate(SolutionFile.Parse(sln.Path), null, null, _buildEventContext, CreateMockLoggingService());
+                instances.ShouldHaveSingleItem();
+                if (!name.Equals("name.that.does.Not.Affect.The.Build.targets"))
+                {
+                    instances[0].Targets["Build"].AfterTargets.ShouldBe("NonsenseTarget");
```
Comment (rainersigwald) [inline src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs]: I don't think this is right. When defined in `before`, the dummy target from the bug should be overridden by the generated target "in the body" of the metaproject.

Have you validated that this change behaves correctly using the repro steps from https://github.com/microsoft/msbuild/issues/5071#issuecomment-578863667?

Comment (Forgind) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs]: Ah, I think this was a design issue. I thought it would be best for the user's version to override the generated version no matter what. I can change it.

File: src/Build/Construction/Solution/SolutionProjectGenerator.cs [hunk 3]
```diff
@@ -1969,7 +1969,13 @@ private static void AddTraversalReferencesTarget(ProjectInstance traversalProjec
                 outputItemAsItem = "@(" + outputItem + ")";
             }
 
-            ProjectTargetInstance target = traversalProject.AddTarget(targetName ?? "Build", String.Empty, String.Empty, outputItemAsItem, null, String.Empty, String.Empty, String.Empty, String.Empty, false /* legacy target returns behaviour */);
+            string correctedTargetName = targetName ?? "Build";
+
+            if (traversalProject.Targets.Select(target => target.Key).Contains(correctedTargetName))
+            {
+                traversalProject.RemoveTarget(correctedTargetName);
+            }
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/SolutionProjectGenerator.cs]: You can just do this unconditionally; `RemoveTarget` doesn't throw if it's not there.

Comment (rainersigwald) [reply src/Build/Construction/Solution/SolutionProjectGenerator.cs]: But this depends on the "how did pre-16.4 behave" question WRT having stub targets in before/after.

Comment (Forgind) [reply src/Build/Construction/Solution/SolutionProjectGenerator.cs]: Sorry—I should have mentioned this rather than just pushing the change. In 16.3, if you have a before...targets or an after...targets with a Build target, the Build target is overwritten by the generated target.

**Comment by tg73** [comment]
I've just run into the situation where I can no longer redefine the Build target, for example via `Directory.Solution.targets` - my redefinition of the Build target is silently ignored. This appears to be due to this 'fix'. I can redefine any other target (such as Restore). Why is this considered a desirable restriction?

**Comment by Forgind** [comment]
Can you define the Build target by putting it in a separate file that you import in Directory.Build/Solution.props? I think Directory.Solution.targets comes in after the dummy Build target was added.

**Comment by tg73** [comment]
@Forgind Apologies for the delay, vacation. No, your suggestion does not work. The custom `build` target is ignored. Looking at the code, and with the disclaimer that this is my naive, non-expert understanding:

These lines in `CreateTraversalInstance` appear to seek to retain any custom definition of the standard targets, removing only the placeholder empty targets, and then call `AddStandardTraversalTargets` apparently with the intention to add in the full versions *only* of those targets that have already been removed:

https://github.com/Forgind/msbuild/blob/1d845f30213e9ba4f36d4d5a366c0cc8285eed6e/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L986-L997

However, `AddStandardTraversalTargets` calls `AddTraversalReferencesTarget` for each standard target, which forcibly removes *any* existing target. This appears to undermine the intent of `CreateTraversalInstance`:

https://github.com/Forgind/msbuild/blob/3e49893950c9a5e9f39a4d887b93810946361eef/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L1961-L1977

An earlier version of `AddTraversalReferencesTarget` appears to have suitable conditional logic in place:

https://github.com/Forgind/msbuild/blob/fb82bc8216051c467850de04fe24e42026a02167/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L1964-L1977
