### PR TITLE
Unset global TargetFramework properties for synthetic project references

### LINKED ISSUE #3626: Upgrading to MSBuild 15.8 causes incorrect TargetFramework property in ProjectReference builds
### Steps to reproduce
You'll need VS 2017 with C++ tools to do this.
```
git clone https://github.com/aspnet/IISIntegration --branch namc/repro-netsdk1005
build.cmd /bl /p:SkipTests=true
```

### Expected  behavior
This project builds just fine with MSBuild 15.7. It should continue to do so in 15.8.

Build log for compiling this project with the 2.1.302 SDK: 
[2_1_302.binlog.zip](https://github.com/Microsoft/msbuild/files/2295693/2_1_302.binlog.zip)

### Actual behavior
The project fails to build

> C:\b\w\1973e9914e89f587.dotnet\x64\sdk\2.1.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1005: Assets file 'C:\b\w\1973e9914e89f587\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project.

Build log for compiling this project with the 2.1.400 SDK: 
[2_1_400.binlog.zip](https://github.com/Microsoft/msbuild/files/2295685/2_1_400.binlog.zip)

Some how a build of Microsoft.AspNetCore.Server.IIS.csproj is getting triggered with "TargetFramework=netcoreapp2.2" even though [this project only has `<TargetFramework>netstandard2.0</TargetFramework>`](https://github.com/aspnet/IISIntegration/blob/6440545c4a1a170de19ca80c1cf24ff346a005b1/src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.csproj#L4).

image

### Environment data
`dotnet msbuild -version`
```
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.166.59604
```
OS info: Windows 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): dotnet cli 2.1.400

cc @rainersigwald @dsplaisted @nguerrera

### PR DESCRIPTION
**Pull request by dasMulli**
Fixes #3626

Since the synthetic p2p won't re-negotiate a `TargetFramework` value to set due to the `SkipGetTargetFrameworkProperties` metadata, remove the the global property from moving across the reference by setting it as `GlobalPropertiesToRemove` metadata.

cc @rainersigwald @AndyGerlicher @jeffkl @nguerrera @natemcmaster

### CODE REVIEW

**Comment by dasMulli** [comment]
test Windows_NT Build for CoreCLR 
test Windows_NT Build for Full

**Comment by dasMulli** [comment]
the windows machines seem to fail on network errors

File: src/Tasks/ResolveProjectBase.cs [hunk 1]
```diff
@@ -277,6 +277,7 @@ protected void AddSyntheticProjectReferences(string currentProjectAbsolutePath)
                     item.SetMetadata("LinkLibraryDependencies", "false");
                     item.SetMetadata("CopyLocal", "false");
                     item.SetMetadata("SkipGetTargetFrameworkProperties", "true");
+                    item.SetMetadata("GlobalPropertiesToRemove", "TargetFramework");
```
Comment (rainersigwald) [inline src/Tasks/ResolveProjectBase.cs]: Should we do RID as well?

Comment (dasMulli) [reply src/Tasks/ResolveProjectBase.cs]: I thought about this as well but:
* building a solution with `-r RID` is prone to lots of issues anyway. But if for some reason it works, the synthetic reference wouldn't cause an additional RID-less build.
* bullding a project with `-r RID` doesn't have this synthetic reference
* a project with a fixed RID doesn't set it as a global property

It would only help if you'd have an additional p2p reference with `AdditionalProperties="RuntimeIdentifier=osx-x64"`.

But on the other hand, it shouldn't do any harm under normal circumstances.

Comment (rainersigwald) [reply src/Tasks/ResolveProjectBase.cs]: I find that convincing! Let's leave as is.

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for CoreCLR
@dotnet-bot test Windows_NT Build for Full

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Full

**Comment by rainersigwald** [comment]
Talked to @AndyGerlicher offline: let's take this for 15.9 and leave open the option of pulling it into 15.8 if too many more folks run into it.

**Comment by dasMulli** [comment]
(rebased onto 15.9)

**Comment by rainersigwald** [comment]
Sorry, misclick--but I'd rather it not be rebased, so we can just merge it into 15.8 if we do need it for servicing.

**Comment by dasMulli** [comment]
undid the rebase (re-cherry-picked onto 15.8). I only see an "out-of-date with the base branch" warning, don't know if current policies now allow merging this.

**Comment by rainersigwald** [comment]
Ahh, that would have made me do the same! I relaxed the branch protection to be more in line with what I was asking for. Sorry for the run-around!

**Comment by nguerrera** [comment]
(Aside: I hate that up-to-date check, and it always manages to turn on with new branches.)

**Comment by dasMulli** [comment]
> Sorry for the run-around!

No problem at all.
Funnily enough, both deep git and msbuild knowledge are generally considered to be dark sorcery.
I'm only one tech stack away from becoming a Sith Lord.
