### PR TITLE
Project Element cloning asks a new hook if it is OK to clone attributes

### LINKED ISSUE #1319: DeepCopyFrom fails with Metadata as Attribute
DeepCopyFrom fails when it attempts to copy an element with metadata as attribute. This leads to an exception thrown and a partially copied project.

```
"The element <A> beneath element <Compile> is invalid because a child element with that name already exists"
```

``` Csharp
string testProject =
  @"<?xml version=""1.0"" encoding=""utf-8""?>
  <Project xmlns = ""http://schemas.microsoft.com/developer/msbuild/2003"">
    <ItemGroup>
      <Compile Include=""Class1.cs"" A=""a"" />
      <Compile Include=""Class2.cs"" />
    </ItemGroup>
  </Project>";

  var attributeProject = ProjectRootElement.Create(XmlReader.Create(new StringReader(testProject)));
  var elementProject = ProjectRootElement.Create();
  try
  {
    elementProject.RemoveAllChildren();
    elementProject.DeepCopyFrom(attributeProject);
  }
  catch (Exception e) // InvalidProjectException thrown
  {
  }

  Assert.AreEqual(elementProject.Items.Count, attributeProject.Items.Count); // Fails! "Class2.cs" is missing.
```

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes #1319

### CODE REVIEW

**Comment by basoundr** [comment]
@cdmihai Could you have this checked-in soon and have an insertion in WPT? We can get this change to RC2. Without this change, persisting the Version Metadata as an Attribute crashes VS.

File: src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs [hunk 1]
```diff
@@ -131,17 +131,22 @@ internal void ChangeName(string newName)
...
-            if (isKnownAttribute || !isValidMetadataNameInAttribute)
+            if (!AttributeNameCanRepresentMetadata(name))
             {
                 ProjectErrorUtilities.ThrowInvalidProject(parentLocation, "InvalidMetadataAsAttribute", name, parentName);
             }
         }
 
+        internal static bool AttributeNameCanRepresentMetadata(string name)
+        {
+            bool isReserverdAttributeName;
```
Comment (rainersigwald) [inline src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs]: typo: `Reserverd`

File: src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs [hunk 2]
```diff
@@ -1204,6 +1205,42 @@ public void DeepCloneWithProjectExtensionsElementOfXml()
...
+        </B>
+        <C Include=`c`/>
+      </ItemGroup>
+    </Target>
+
+  </Project>";
+
+            var pre = ProjectRootElement.Create(XmlReader.Create(new StringReader(ObjectModelHelpers.CleanupFileContents(project))));
+
+            ValidateDeepCloneAndCopyFrom(pre);
```
Comment (rainersigwald) [inline src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs]: And this test did repro the crash, right?

File: src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs [hunk 3]
```diff
@@ -131,17 +131,22 @@ internal void ChangeName(string newName)
...
-            ProjectParser.CheckMetadataAsAttributeName(name, out isKnownAttribute, out isValidMetadataNameInAttribute);
-
-            if (isKnownAttribute || !isValidMetadataNameInAttribute)
+            if (!AttributeNameCanRepresentMetadata(name))
             {
                 ProjectErrorUtilities.ThrowInvalidProject(parentLocation, "InvalidMetadataAsAttribute", name, parentName);
             }
         }
 
+        internal static bool AttributeNameCanRepresentMetadata(string name)
```
Comment (rainersigwald) [inline src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs]: I find this name confusing, but I can't think of one that's unambiguously better. `AttributeIsMetadata`? `AttributeIsNotReserved`?

Fine to go with current if we can't think of something better.

Comment (cdmihai) [inline src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs]: How about `AttributeNameIsValidMetadataName`?

File: src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs (hunk 2 above)
Comment (cdmihai) [inline src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs]: Yup, it had failed with the same `"The element <A> beneath element <Compile> is invalid because a child element with that name already exists"`. The `RemoveAllChilddren` from @jviau's repro did not seem necessary to cause the crash.

File: src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs (hunk 3 above)
Comment (rainersigwald) [inline src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs]: I think that's better, yeah.
