### PR TITLE
Fix #2367: incorrect evaluation of VisualStudioInstallRootDirectory

### LINKED ISSUE #2367: Incorrect value for MSBuildExtensionsPath when using Microsoft.Build.dll in 64bits
Using the following project:
https://github.com/emmanuelguerin/dotnet-builder/tree/bug64bits

When running the project in 32 bits mode using MsBuild inside Visual Studio 2017 Entreprise 15.2 (build configuration Debug32), the build script returns correct `MSBuildExtensionsPath` value:
```
Extension Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild
```

When running the project in 64 bits mode (build configuration Debug) and using the DLL inside:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64`, the `MSBuildExtensionsPath` variable is incorrectly initialized to:

```
Extension Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\MSBuild
```

### PR DESCRIPTION
**Pull request by emmanuelguerin**
When using TryFromMSBuildAssembly with Microsoft.Build.dll inside the amd64 directory, the VisualStudioInstallRootDirectory
is incorrectly evaluated as if in 32 bits mode.

Fix for #2367

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
This looks right. Thanks for the contribution! Before taking this I'd like to see a unit test for the scenario. There is a BuildEnvironment test class where all of this can be mocked. If you aren't able to get to that we can look into adding the test as well. Just let us know.

**Comment by AndyGerlicher** [comment]
@emmanuelguerin I added a unit test for the scenario that fails without your change. I also had to force push your branch (you were several hundred commits behind master). Just FYI. And thanks again for the contribution!

File: src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs [hunk 1]
```diff
@@ -385,6 +385,44 @@ public void BuildEnvironmentNoneWhenNotAvailable()
             }
         }
 
+        [Fact]
+        [Trait("Category", "nonlinuxtests")]
+        [Trait("Category", "nonosxtests")]
```
Comment (rainersigwald) [inline src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs]: `[PlatformSpecific(Xunit.PlatformID.Windows)]` instead?

Comment (AndyGerlicher) [inline src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs]: Think I'd rather change these in bulk. When I tried to update the version of xunit and get rid of BuildTools a while back there were some discrepancies (don't remember details right now).

**Comment by emmanuelguerin** [comment]
Thanks for the tests! Do you know in which version this fix will eventually get released?
