### PR TITLE
Fix a race condition in ToolLocationHelper

### LINKED ISSUE #3036: ToolLocationHelper.GetPathToReferenceAssemblies not thread safe
*Sadly no clear repro on this one but I think a fix can be found by just looking at the code (which I did briefly).*

I'm evaluating in // many .csproj from a huge solution (hundreds of projects) to get their output path. Sometimes on some build machines I get:
```
The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NETFramework, v4.6.1, '', AnyCPU)" cannot be evaluated. 
Collection was modified; enumeration operation may not execute. 
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets
```

I'm using Microsoft.Build@15.5.180 and my .sln is a VS2015 one.

When looking at the code:
https://github.com/Microsoft/msbuild/blob/75e5117ab8be40faad4601904600aceae6bf9ee1/src/Utilities/ToolLocationHelper.cs#L1779
There is some lock around some static variables but I guess some might be missing when iterating on the returned list. Maybe use ConcurrentDictionnary ?

### PR DESCRIPTION
**Pull request by AntonLapounov**
Fixes #3036.  Modifying the `dotNetFrameworkReferenceAssemblies` collection after publishing it bumps its version and breaks the `foreach` loop in the `GetPathToStandardLibraries` method.

### CODE REVIEW

File: src/Utilities/ToolLocationHelper.cs [hunk 1]
```diff
@@ -2108,24 +2108,22 @@ public static IList<string> GetPathToReferenceAssemblies(string targetFrameworkR
...
-            lock (s_locker)
-            {
-                s_cachedReferenceAssemblyPaths[referenceAssemblyCacheKey] = dotNetFrameworkReferenceAssemblies;
-            }
-
             for (int i = 0; i < dotNetFrameworkReferenceAssemblies.Count; i++)
             {
                 if (
                     !dotNetFrameworkReferenceAssemblies[i].EndsWith(
                         Path.DirectorySeparatorChar.ToString(),
```
Comment (danmosemsft) [inline src/Utilities/ToolLocationHelper.cs]: There is an unnecessary allocation of a string here. The fix is 
` !dotNetFrameworkReferenceAssemblies[i].EndsWith(Path.DirectorySeparatorChar)`
Which is an ordinal comparison anyway.

Comment (AntonLapounov) [reply src/Utilities/ToolLocationHelper.cs]: The `char` overload was added in .NET Core 2.0; it won't compile for the desktop .NET Framework.

Comment (danmosemsft) [reply src/Utilities/ToolLocationHelper.cs]: Oh yes, I see I signed off 😃 

Well it can just do the same thing - check length then use indexer.

Comment (rainersigwald) [reply src/Utilities/ToolLocationHelper.cs]: We have a centralized mechanism--`FileUtilities.EndsWithSlash()`.

**Comment by danmosemsft** [comment]
@rainiersigwald hard to answer without knowing the bug bar. I guess its good to fix race conditions when they are found because they are unpredictable in their impact.in this case the risk seems very low.

File: src/Utilities/ToolLocationHelper.cs (hunk 1 above)
Comment (AntonLapounov) [reply src/Utilities/ToolLocationHelper.cs]: @rainersigwald `FileUtilities.EnsureTrailingSlash` is even more suitable here, however, both of them slightly change the semantics since they also check for `Path.AltDirectorySeparatorChar` at the end of the path.  Any semantic changes should be done separately.

**Comment by AntonLapounov** [comment]
Thank you for reviewing this so quickly!  Anyone with write access — please merge this fix.  Our compiler check-in system has been intermittently hitting this race condition for many months now.

**Comment by rainersigwald** [comment]
Oops, I should have put an explicit waiting on this--I think we should have taken it for 15.9. Oh well, can always backport.

**Comment by cdmihai** [comment]
Going to cherry pick it into 15.9stg

**Comment by cdmihai** [comment]
https://github.com/Microsoft/msbuild/pull/3543

File: src/Utilities/ToolLocationHelper.cs (hunk 1 above)
Comment (danmosemsft) [reply src/Utilities/ToolLocationHelper.cs]: https://github.com/Microsoft/msbuild/issues/3544
