### PR TITLE
Add Version and fix ProjectPath in SdkResolverContext

### LINKED ISSUE #2097: SdkResolverContext should provide msbuild version
This is needed for dotnet/cli#6585

@AndyGerlicher

### PR DESCRIPTION
**Pull request by AndyGerlicher**
* Adds MSBuild version.
 * Fix ProjectFilePath to be the full path to the project (equivalent to
 '$(MSBuildProjectFullPath)').
 * Fix issue where SolutionFilePath can be set by Common targets to
 '*Undefined*'. When this is the case, set to null for consistency.

Closes #2097, #2083, #2082 

Looking into adding some tests, will have a followup commit.

### CODE REVIEW

File: src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs [hunk 1]
```diff
@@ -40,9 +41,10 @@ internal SdkResolution(SdkResolverLoader sdkResolverLoader)
         /// <param name="buildEventContext">Build event context for logging.</param>
         /// <param name="sdkReferenceLocation">Location of the element within the project which referenced the SDK.</param>
         /// <param name="solutionPath">Path to the solution if known.</param>
+        /// <param name="projectPath">Path to the project being.</param>
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs]: you accidentally a word.

File: src/Framework/Sdk/SdkResolverContext.cs [hunk 2]
```diff
@@ -22,5 +24,10 @@ public abstract class SdkResolverContext
         ///     Path to the solution file being built, if known. May be null.
         /// </summary>
         public virtual string SolutionFilePath { get; protected set; }
+
+        /// <summary>
+        ///     Version of MSBuild currently running.
```
Comment (rainersigwald) [inline src/Framework/Sdk/SdkResolverContext.cs]: Clarify full git-height version vs. assembly version.

File: src/Build/Evaluation/Evaluator.cs [hunk 3]
```diff
@@ -2370,12 +2370,15 @@ private List<ProjectRootElement> ExpandAndLoadImports(string directoryOfImportin
 
             if (importElement.ParsedSdkReference != null)
             {
-                // Try to get the solution path when available.
+                // Try to get the path to the solution and project being built. If the solution path equals "*Undefined*" 
+                // (hard coded in Microsoft.Common.CurrentVersion.targets) set to null for consistency.
                 var solutionPath = _data.GetProperty(SolutionProjectGenerator.SolutionPathPropertyName)?.EvaluatedValue;
+                var projectPath = _data.GetProperty(ReservedPropertyNames.projectFullPath)?.EvaluatedValue;
```
Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs]: Isn't there a `GetPropertyValue()`?

Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs]: Isn't there a `GetPropertyValue()`?

Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs]: Is getting this out of the reserved property the only way to get the information at this layer? I don't like that (even though AFAIK it's immutable it seems unclean).

File: src/Build/Evaluation/Evaluator.cs [hunk 4]
```diff
@@ -2370,12 +2370,15 @@ private List<ProjectRootElement> ExpandAndLoadImports(string directoryOfImportin
 
             if (importElement.ParsedSdkReference != null)
             {
-                // Try to get the solution path when available.
+                // Try to get the path to the solution and project being built. If the solution path equals "*Undefined*" 
+                // (hard coded in Microsoft.Common.CurrentVersion.targets) set to null for consistency.
```
Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs]: Instead of 

> If the solution path equals "*Undefined*" (hard coded in Microsoft.Common.CurrentVersion.targets) set to null for consistency.

Maybe

> The solution path is not directly known in MSBuild. It is passed in as a property either by the VS project system or by MSBuild's solution metaproject. Microsoft.Common.CurrentVersion.targets sets the value to `*Undefined*` when not set, and for backward compatibility, we shouldn't change that. But resolvers should be exposed to a string that's null or a full path, so correct that here.

File: src/Build/Evaluation/Evaluator.cs [hunk 5]
```diff
@@ -2370,12 +2370,15 @@ private List<ProjectRootElement> ExpandAndLoadImports(string directoryOfImportin
...
                 var solutionPath = _data.GetProperty(SolutionProjectGenerator.SolutionPathPropertyName)?.EvaluatedValue;
+                var projectPath = _data.GetProperty(ReservedPropertyNames.projectFullPath)?.EvaluatedValue;
+                if (solutionPath == "*Undefined*") solutionPath = null;
```
Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs]: Nit: put this line next to the acquisition of `solutionPath` (above `projectPath)`.

File: src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs [hunk 6]
```diff
@@ -100,6 +102,16 @@ internal SdkResolution(SdkResolverLoader sdkResolverLoader)
             return null;
         }
 
+        internal void InitializeForTests(IList<SdkResolver> resolvers, ILoggingService logger, BuildEventContext buildEventContext, ElementLocation location)
+        {
+            _resolvers = resolvers;
+        }
+
+        internal void ResetInitializeForTests()
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs]: Where is this used/how is it (and `InitializeForTests`) related to this change?

**Comment by rainersigwald** [comment]
@dotnet-bot test ci please

**Comment by rainersigwald** [comment]
@dotnet-bot test this please
