### PR TITLE
Permit a task to disable MSB4181 Fixes #5203

### LINKED ISSUE #2036: Log our own error if a task returned false but didn't log any errors
If a task violates the implicit expectation that it should return false iff it logged any errors MSBuild fails the build, but doesn't indicate why.

We should consider at least adding a warning, but ideally failing the build (perhaps in strict mode?)

### LINKED ISSUE #5203: MSB4132 is emitted when a task logs errors in custom format
### Steps to reproduce
This is a new issue in VS2019 16.6 Preview 1 with our custom build tasks. The issue looks to have been introduced by [#4940](https://github.com/microsoft/msbuild/pull/4940)

The issue occurs because we use our own custom log format when building within Visual Studio. We use the standard error format during command line builds so there is no problem there. 
Our custom format allows us to give a richer experience navigating errors and populating the Visual Studio Error List (which allows custom columns etc). Essentially we have our own set of RegEx parse routines (similar to CanonicalError in MSBuild). Since we hook the output in IDE builds we can create the appropriate errors in the Visual Studio Error list. This is similar to the default functionality offered by VS [ParseOutputStringForTaskItem](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivslaunchpad.parseoutputstringfortaskitem?view=visualstudiosdk-2019#Microsoft_VisualStudio_Shell_Interop_IVsLaunchPad_ParseOutputStringForTaskItem_System_String_System_UInt32___System_String___System_UInt32___System_String___System_Int32___) However, the build tasks (which use TaskLoggingHelper.LogMessagesFromStream() ) will fail to match the format and incorrectly assume no errors were output. The MSB4132 error is then emitted.

One easy workaround/fix would have been to manually set the TaskLoggingHelper's HasLoggedErrors property, but that is unfortunately is only gettable. The only other simple fix I have is to parse the output for this new MSB4132 error and throw it away. 

It would be useful if there was a way to opt out of this change in behavior. The code change itself seems to have various exemptions and I see other issues raised concerning this, so it would be good to have a simple way for any task to bypass this. 

### Expected behavior
Same as pre 16.6. Don't show: "...error MSB4132: The "[TaskName]" task returned false but did not log an error."

### Actual behavior
"...error MSB4132: The "[TaskName]" task returned false but did not log an error."

### Environment data
OS info:

Visual Studio 16.6 Preview 1

### PR DESCRIPTION
**Pull request by Forgind**
Using IBuildEngine7, one can disable MSB4132 in a task.

Fixes #5203 
Also fixes #2036

### CODE REVIEW

File: src/Utilities/Task.cs [hunk 1]
```diff
@@ -89,6 +89,11 @@ protected Task(ResourceManager taskResources, string helpKeywordPrefix)
         /// </summary>
         public IBuildEngine6 BuildEngine6 => (IBuildEngine6)BuildEngine;
 
+        /// <summary>
+        /// Retrieves the <see cref="IBuildEngine7" /> version of the build engine interface provided by the host.
+        /// </summary>
+        public IBuildEngine6 BuildEngine7 => (IBuildEngine7)BuildEngine;
```
Comment (sae42) [inline src/Utilities/Task.cs]: Shouldn't this return IBuildEngine7?

File: ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs [hunk 2]
```diff
@@ -197,6 +197,7 @@ public abstract partial class Task : Microsoft.Build.Framework.ITask
         public Microsoft.Build.Framework.IBuildEngine4 BuildEngine4 { get { throw null; } }
         public Microsoft.Build.Framework.IBuildEngine5 BuildEngine5 { get { throw null; } }
         public Microsoft.Build.Framework.IBuildEngine6 BuildEngine6 { get { throw null; } }
+        public Microsoft.Build.Framework.IBuildEngine6 BuildEngine7 { get { throw null; } }
```
Comment (sae42) [inline ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs]: Shouldn't this return IBuildEngine7?

File: ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs [hunk 3]
```diff
@@ -352,6 +352,7 @@ public abstract partial class Task : Microsoft.Build.Framework.ITask
         public Microsoft.Build.Framework.IBuildEngine4 BuildEngine4 { get { throw null; } }
         public Microsoft.Build.Framework.IBuildEngine5 BuildEngine5 { get { throw null; } }
         public Microsoft.Build.Framework.IBuildEngine6 BuildEngine6 { get { throw null; } }
+        public Microsoft.Build.Framework.IBuildEngine6 BuildEngine7 { get { throw null; } }
```
Comment (sae42) [inline ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs]: Shouldn't this return IBuildEngine7?

File: src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs [hunk 4]
```diff
@@ -670,6 +670,25 @@ public void LogTelemetry(string eventName, IDictionary<string, string> propertie
 
         #endregion
 
+        #region IBuildEngine7 Members
+        /// <summary>
+        /// Enables or disables emitting MSB4134 to log when a task fails without logging errors
+        /// </summary>
+        public void SetEnableMSB4134(bool enableError)
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs]: Why is this an explicit set method rather than a setter?

File: src/Build/Resources/Strings.resx [hunk 5]
```diff
@@ -1064,8 +1064,8 @@
     </comment>
   </data>
   <data name="TaskReturnedFalseButDidNotLogError">
-    <value>MSB4132: The "{0}" task returned false but did not log an error.</value>
-    <comment>{StrBegin="MSB4132: "}</comment>
+    <value>MSB4134: The "{0}" task returned false but did not log an error.</value>
```
Comment (rainersigwald) [inline src/Build/Resources/Strings.resx]: This appears to have been used, too:

```
MSB4134: DefaultToolsVersion cannot be set after a project has been loaded into the Engine.
```

That's coming entirely from the `Deprecated\Engine` folder, but we still shouldn't recycle.

File: src/Framework/IBuildEngine7.cs [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+
+namespace Microsoft.Build.Framework
+{
+    /// <summary>
+    /// This interface extends <see cref="IBuildEngine6" /> to allow tasks to set whether they want to
+    /// log an error when a task returns without logging an error.
+    /// </summary>
+    public interface IBuildEngine7 : IBuildEngine6
+    {
+        public void SetEnableMSB4134(bool errorEnabled);
```
Comment (rainersigwald) [inline src/Framework/IBuildEngine7.cs]: Don't include the error code in the name of this method. Give it a descriptive name instead, like maybe
```suggestion
        public void AllowFailureWithoutError(bool errorEnabled);
```
?

File: src/Tasks.UnitTests/AssemblyDependency/AssemblyFoldersFromConfig_Tests.cs [hunk 7]
```diff
@@ -93,7 +93,7 @@ public void AssemblyFoldersFromConfigPlatformSpecificAssemblyFirstTest()
         }
 
         [Fact]
-        public void AasemblyFoldersFromConfigNormalizeNetFrameworkVersion()
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/AssemblyDependency/AssemblyFoldersFromConfig_Tests.cs]: Please separate this into its own PR.

File: src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs (hunk 4 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs]: You mean a property with `{get; set;}`? I don't think you can access that with reflection.

Comment (rainersigwald) [reply src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs]: You can, with [`Type.GetProperty`](https://docs.microsoft.com/dotnet/api/system.type.getproperty?view=netframework-4.8#System_Type_GetProperty_System_String_)

**Comment by rainersigwald** [comment]
Team triage: we'd like to reserve `IBuildEngine7` for some changes going into 16.7 that are already planned. Let's delay this change until then as well.

**Comment by sae42** [comment]
@rainersigwald If this fix has to be deferred to 16.7 is there any chance of reverting the original change that caused this issue until 16.7 also? Failing that, please at least correct the error code so that it will be consistent between releases.

File: src/Tasks.UnitTests/AssemblyDependency/AssemblyFoldersFromConfig_Tests.cs (hunk 7 above)
Comment (rainersigwald) [reply src/Tasks.UnitTests/AssemblyDependency/AssemblyFoldersFromConfig_Tests.cs:96]: Ping
