### PR TITLE
Respect transforms in lazy eval

### LINKED ISSUE #5445: Lazy evaluation optimizations don't respect item transforms
`Update` and `Remove` don't respect item transforms at evaluation time; they apply to all items instead of just the ones that were selected by the item transform.

This was the case for `Update` for a long time; `Remove` was working correctly until #5350.

### Steps to reproduce

Project file
```xml
<Project>
  <ItemGroup>
    <Foo Include="C:\*" />
    <Foo Include="x" />

    <!-- <Foo Update="@(Foo->WithMetadataValue('Filename', 'x'))" Bar="Baz" /> -->
    <Foo Remove="@(Foo->WithMetadataValue('Filename', 'x'))" />
  </ItemGroup>

  <Target Name="Go">
    <Message Importance="High"
             Text="Foo=@(Foo->'%(Filename) %(Bar)')" />
  </Target>
</Project>
```

### Expected behavior

Only the `x` item removed/updated

### Actual behavior

```
Go:
  Foo=
```

### Environment data
`msbuild /version` output: `16.7.0-preview-20309-02+d6862eb21`

### PR DESCRIPTION
**Pull request by rainersigwald**
Fixes #5445 by checking to see if an item function is invoked (the captured
expression has subcaptures) before optimizing operations on same-item
captures.

Added regression tests and improved some asserts that didn't really help me when they fired.

fyi @cdmihai, @safern

### CODE REVIEW

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs [hunk 1]
```diff
@@ -120,6 +120,39 @@ public void RemoveShouldPreserveIntermediaryReferences(string content)
             ObjectModelHelpers.AssertItems(new string[0], itemsForI2);
         }
 
+        [Fact]
+        public void RemoveRespectsItemTransform()
+        {
+            var content = @"
+                            <i Include='a;b;c' />
+
+                            <i Remove='@(i->WithMetadataValue(`Filename`, `b`))' />";
```
Comment (safern) [inline src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:129]: Curious, why use `Filename` instead of `Identity`?

File: src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs [hunk 2]
```diff
@@ -342,6 +346,14 @@ protected static bool ItemspecContainsASingleItemReference(ItemSpec<P, I> itemSp
                     return false;
                 }
 
+                // If the itemSpec is a single call to an item function, like @(X->Something(...)), it may get this
```
Comment (safern) [inline src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:349]: I guess only item function transforms are impacted by this since I can't do `@(X-> '%(Identity)')` in lazy evaluations?

Comment (cdmihai) [reply src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:349]: That's still an item transform. It should be supported in lazy evaluations.
The safest is for this function to reject all transforms, since there's no guarantee the transform would produce the same result as the original item.

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs [hunk 3]
```diff
@@ -120,6 +120,39 @@ public void RemoveShouldPreserveIntermediaryReferences(string content)
             ObjectModelHelpers.AssertItems(new string[0], itemsForI2);
         }
 
+        [Fact]
```
Comment (cdmihai) [inline src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:123]: I'd add tests for both types of item transforms:
- item functions `@(foo->function())`
- string templatey thing: `@(foo->'%(filename)')`

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:129]: I was copy/pasting from the real repro :) `Identity` does make more sense.

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs [hunk 4]
```diff
@@ -120,6 +120,43 @@ public void RemoveShouldPreserveIntermediaryReferences(string content)
...
+        {
+            var content = @"
+                            <i Include='a;b;c' />
+
+                            <i Update='@(i->WithMetadataValue(`Identity`, `b`))'>
+                                <m1>m1_updated</m1>
+                            </i>
+                            <i Update=`@(i->'%(Identity)')`>
+                                <m2>m2_updated</m2>
+                            </i>";
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:148]: This is the wrong direction; I should make sure it _doesn't_ apply when it shouldn't

**Comment by ericstj** [comment]
cc @mmitche who suggested getting this into Preview7

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs [hunk 5]
```diff
@@ -120,6 +120,43 @@ public void RemoveShouldPreserveIntermediaryReferences(string content)
...
         }
 
+        [Fact]
+        public void RemoveRespectsItemTransform()
+        {
+            var content = @"
+                            <i Include='a;b;c' />
+
+                            <i Remove='@(i->WithMetadataValue(`Identity`, `b`))' />
+                            <i Remove='@(i->`%(Extension)`)' /><!-- should do nothing -->";
```
Comment (Forgind) [inline src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:130]: nit:
```suggestion
                            <i Remove='@(i->`%(Extension)`)' /> <!-- should do nothing -->";
```

File: src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs [hunk 6]
```diff
@@ -120,6 +120,43 @@ public void RemoveShouldPreserveIntermediaryReferences(string content)
...
+        [Fact]
+        public void UpdateRespectsItemTransform()
+        {
+            var content = @"
+                            <i Include='a;b;c' />
+
+                            <i Update='@(i->WithMetadataValue(`Identity`, `b`))'>
+                                <m1>m1_updated</m1>
+                            </i>
+                            <i Update=`@(i->'%(Extension)')`><!-- should do nothing -->
```
Comment (Forgind) [inline src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs:146]: nit:
```suggestion
                            <i Update=`@(i->'%(Extension)')`> <!-- should do nothing -->
```

File: src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs [hunk 7]
```diff
@@ -342,6 +346,14 @@ protected static bool ItemspecContainsASingleItemReference(ItemSpec<P, I> itemSp
...
+                // far, but shouldn't be treated as a single reference: the item function may return entirely
+                // different results from a bare reference like @(X).
+                if (itemExpressionFragment.Capture.Captures is object)
+                {
+                    return false;
```
Comment (Forgind) [inline src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:354]: Should this always return false or should it occasionally return true? I think this is only used for performance, so it doesn't matter if it has false negatives now, but I'd like to see if I understand it correctly. Also could be relevant if we start using it elsewhere.

File: src/Shared/UnitTests/ObjectModelHelpers.cs [hunk 8]
```diff
@@ -243,7 +243,10 @@ public static void AssertItems(string[] expectedItems, IList<TestItem> items, Di
                 expectedItems.ShouldNotBeEmpty();
             }
 
-            for (var i = 0; i < expectedItems.Length; i++)
+            // iterate to the minimum length; if the lengths don't match but there's a prefix match the count assertion below will trigger
```
Comment (Forgind) [inline src/Shared/UnitTests/ObjectModelHelpers.cs:246]: Could we just move the assert up? Seems simpler.

File: src/Shared/UnitTests/ObjectModelHelpers.cs [hunk 9]
```diff
@@ -243,7 +243,10 @@ public static void AssertItems(string[] expectedItems, IList<TestItem> items, Di
...
+            int minimumLength = Math.Min(expectedItems.Length, items.Count());
```
Comment (Forgind) [inline src/Shared/UnitTests/ObjectModelHelpers.cs:247]:
```suggestion
            int minimumLength = Math.Min(expectedItems.Length, items.Count);
```

File: src/Shared/UnitTests/ObjectModelHelpers.cs (hunk 8 above)
Comment (rainersigwald) [reply src/Shared/UnitTests/ObjectModelHelpers.cs:246]: That was my initial implementation, but it loses a bunch of information in the error message--it's nicer to see the item-level diff if there is one. That helped me chase down a couple of errors in this implementation.

File: src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs (hunk 7 above)
Comment (rainersigwald) [reply src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:354]: It should always return `false`. The question this method answers is "can I just remove/update every item in the group, or do I need to expand the value to match against existing items?"

Renamed it for a bit more clarity there.
