### PR TITLE
Graceful error on metadata expansion failure

### LINKED ISSUE #3476: MSBuild throws internal exception instead of graceful error message when direct metadata evaluation throws IO exceptions
### Steps to reproduce

Project structure with a long path: 
[LongPathException.zip](https://github.com/Microsoft/msbuild/files/2161493/LongPathException.zip)

Project file
```xml
<Project DefaultTarges="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <A Include="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt">
            <M>"%(FullPath)"</M>
        </A>
        <!-- <B Include="@(A->'%(FullPath)')"/> -->
    </ItemGroup>
    
    <Target Name="Build">
        <Message Text="A=%(A.Identity); A.M=%(A.M)" Importance="High"/>
    </Target>
</Project>
```

### Expected  behavior
A build error that specifies the line containing the metadata which could not be evaluated

### Actual behavior

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
This is an unhandled exception in MSBuild -- PLEASE OPEN A BUG AGAINST THE MSBUILD TEAM.
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt". Path: E:\delete\play\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt exceeds the OS max path limit. The fully qualified file name must be less than LegacyWindows characters.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args) in /_/src/Shared/ErrorUtilities.cs:line 304
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(Boolean condition, String resourceName, Object arg0, Object arg1, Object arg2) in /_/src/Shared/ErrorUtilities.cs:line 395
   at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath) in /_/src/Shared/Modifiers.cs:line 608
   at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath) in /_/src/Build/Definition/BuiltInMetadata.cs:line 87
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name) in /_/src/Build/Instance/ProjectItemInstance.cs:line 1728
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName) in /_/src/Build/Instance/ProjectItemInstance.cs:line 1257
   at Microsoft.Build.Execution.ProjectItemInstance.Microsoft.Build.Evaluation.IMetadataTable.GetEscapedValueIfPresent(String itemType, String name) in /_/src/Build/Instance/ProjectItemInstance.cs:line 550
   at Microsoft.Build.Execution.ProjectItemInstance.Microsoft.Build.Evaluation.IMetadataTable.GetEscapedValue(String itemType, String name) in /_/src/Build/Instance/ProjectItemInstance.cs:line 536
   at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.MetadataMatchEvaluator.ExpandSingleMetadata(Match itemMetadataMatch) in /_/src/Build/Evaluation/Expander.cs:line 854
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options) in /_/src/Build/Evaluation/Expander.cs:line 726
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation) in /_/src/Build/Evaluation/Expander.cs:line 260
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.DecorateItemsWithMetadata(ImmutableList`1 items, ImmutableList`1 metadata) in /_/src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:line 169
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.IncludeOperation.MutateItems(ImmutableList`1 items) in /_/src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs:line 138
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:line 56
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.MemoizedOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 194
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.ComputeItems(LazyItemList lazyItemList, ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 386
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.GetItemData(ImmutableHashSet`1 globsToIgnore) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 316
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.<>c.<GetAllItemsDeferred>b__29_0(LazyItemList itemList) in /_/src/Build/Evaluation/LazyItemEvaluator.cs:line 449
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in /_/src/Build/Evaluation/Evaluator.cs:line 773
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext) in /_/src/Build/Evaluation/Evaluator.cs:line 377
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings) in /_/src/Build/Instance/ProjectInstance.cs:line 2576
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings) in /_/src/Build/Instance/ProjectInstance.cs:line 383
   at Microsoft.Build.BackEnd.RequestBuilder.LoadProjectFromFile() in /_/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:line 1170
   at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadProjectFromFile) in /_/src/Build/BackEnd/Shared/BuildRequestConfiguration.cs:line 419
   at Microsoft.Build.BackEnd.RequestBuilder.LoadProjectIntoConfiguration() in /_/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:line 1131
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__58.MoveNext() in /_/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:line 1078
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__50.MoveNext() in /_/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:line 752
```

Moving the metadata into an item transformation leads to a better response:

```xml
<Project DefaultTarges="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <A Include="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt">
            <!-- <M>"%(FullPath)"</M> -->
        </A>
        <B Include="@(A->'%(FullPath)')"/>
    </ItemGroup>
    
    <Target Name="Build">
        <Message Text="A=%(A.Identity); A.M=%(A.M)" Importance="High"/>
    </Target>
</Project>
```

```
E:\delete\play\build.proj(6,12): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt". Path: E:\de
lete\play\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\aaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\1.txt exceeds the OS max path limit. The fully qualified file name must be less than LegacyWindows characters.
```

The `LegacyWindows` part is a separate issue :)

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes #3476

### CODE REVIEW

File: src/Shared/FileUtilities.cs [hunk 1]
```diff
@@ -292,7 +292,7 @@ private static string GetFullPath(string path)
 
                 if (IsPathTooLong(uncheckedFullPath))
                 {
-                    string message = ResourceUtilities.FormatString(AssemblyResources.GetString("Shared.PathTooLong"), path, NativeMethodsShared.OSMaxPathLimit);
+                    string message = ResourceUtilities.FormatString(AssemblyResources.GetString("Shared.PathTooLong"), path, (int)NativeMethodsShared.OSMaxPathLimit);
```
Comment (cdmihai) [inline src/Shared/FileUtilities.cs]: @ccastanedaucf

**Comment by cdmihai** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR

**Comment by cdmihai** [comment]
@dotnet-bot test OSX10.13 Build for CoreCLR

File: src/Build/Evaluation/Expander.cs [hunk 2]
```diff
@@ -799,10 +799,6 @@ internal static string ExpandMetadataLeaveEscaped(string expression, IMetadataTa
 
                     return result;
                 }
-                catch (ArgumentException ex) // Blank metadata name
```
Comment (cdmihai) [inline src/Build/Evaluation/Expander.cs]: @rainersigwald 
I decided to not catch `ArgumentException` here, since I could not get it failing with blank metadata. Also, this method does a bit more than the other try catch protected places which just compute metadata.

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Full
