### PR TITLE
[Static Graph] Skipped results do not trigger cache miss enforcement

### LINKED ISSUE #4343: Graph cache miss constraint triggers when it shouldn't on skipped targets
### Steps to reproduce

1.csproj, the root:
```xml
<Project DefaultTargets="Build">

  <ItemGroup>
    <ProjectReference Include="2.csproj" />

    <ProjectReferenceTargets Include="Build" Targets=".default;A" />
  </ItemGroup>

  <Target Name="Build">
    <MSBuild Projects="@(ProjectReference)" Targets="A" />
    <MSBuild Projects="@(ProjectReference)" />
  </Target>

</Project>
```

2.csproj, the reference:
```xml
<Project DefaultTargets="DefaultTarget" InitialTargets="InitialTarget">

  <Target Name="A" Condition="true == false"/>

  <Target Name="DefaultTarget" Condition="true == false"/>

  <Target Name="InitialTarget" Condition="true == false"/>

</Project>
```

Command line
```
msbuild 1.csproj /graph /isolate
```
### Expected  behavior

Build succeeds

### Actual behavior

```
  E:\delete\CentralPackageVersioning\SimplifiedNoSdks\2.csproj : error : MSB4252: Project "E:\delete\CentralPackageVersioning\SimplifiedNoSdks\1.csproj" has a reference to "E:\delete\CentralPackageVersioning\SimplifiedNoSdks\2.csproj" (A target(s)) but the build resul
t for the reference is not in the engine cache. In isolated builds this could mean one of the following:
E:\delete\CentralPackageVersioning\SimplifiedNoSdks\2.csproj : error :     - the reference was not explicitly specified as a ProjectReference item in "E:\delete\CentralPackageVersioning\SimplifiedNoSdks\1.csproj"
E:\delete\CentralPackageVersioning\SimplifiedNoSdks\2.csproj : error :     - the reference was not included in the provided input caches
E:\delete\CentralPackageVersioning\SimplifiedNoSdks\2.csproj : error :     - the reference was called with a target which is not specified in the ProjectReferenceTargets item in "E:\delete\CentralPackageVersioning\SimplifiedNoSdks\1.csproj"
```

### Cause and fix

The results cache considers it a cache miss when either the requested targets, the initial targets, or the default targets (if no requested targets) are skipped: https://github.com/Microsoft/msbuild/blob/f0efb1cd0f2c91290e5e58862fc9ed56532da00b/src/Build/BackEnd/Components/Caching/ResultsCache.cs#L154-L158

The graph should be okay if any of these get skipped: a parent project requested some targets in a reference, the targets were considered, but conditioned to false.

The `BuildResult.SatisfyRequest` method should be changed to provide more detailed outcomes so the graph can still consider it a cache hit on skipped targets. Or maybe `BuildParameters.IsolateProjects` should force `BuildResult.SatisfyRequest` to always be called with `skippedResultsAreOK = true`

### PR DESCRIPTION
**Pull request by cdmihai**
Closes #4343

PR is based on #4379, review that one first.

If a project has skipped targets, subsequent requests for those targets trigger the re-execution of the targets. This erroneously causes the static graph constraint of no cache misses. To fix it, `BuildParameters.IsolateProjects` will cause the `ResultsCache` to not issue a cache miss on skipped targets. This seems quite reasonable because in an isolated graph build, a project is visited only once.

### CODE REVIEW

File: src/Build/BackEnd/Shared/BuildRequestConfiguration.cs [hunk 1]
```diff
@@ -710,6 +714,47 @@ public List<string> GetAfterTargetsForDefaultTargets(BuildRequest request)
...
+
+                    if (items.Count == 0 || items.All(i => string.IsNullOrWhiteSpace(i.EvaluatedInclude)))
+                    {
+                        return _ => false;
+                    }
+
+                    var fragments = items.SelectMany(i => ExpressionShredder.SplitSemiColonSeparatedList(i.EvaluatedInclude));
+                    var glob = new CompositeGlob(
+                        fragments
+                            .Select(s => MSBuildGlob.Parse(Project.Directory, s)));
```
Comment (danmosemsft) [inline src/Build/BackEnd/Shared/BuildRequestConfiguration.cs]: Is this perf sensitive code? Historically we kept LINQ out of the codebase, or at least out of perf sensitive places. It tends to have hidden costs.

File: src/Build/Resources/xlf/Strings.cs.xlf [hunk 2]
```diff
@@ -106,6 +106,13 @@
         <note>
       {StrBegin="MSB4250: "}
       LOCALIZATION:  Do not localize the following words: ProjectGraph, ProjectReference, ToolsVersion.
+    </note>
+      </trans-unit>
+      <trans-unit id="SkippedConstraintsOnRequest">
+        <source>MSB4260: Project {0} skipped graph isolation constraints on referenced project {1}</source>
```
Comment (danmosemsft) [inline src/Build/Resources/xlf/Strings.cs.xlf]: I think the other messages put " around paths.

File: src/Build/BackEnd/Shared/BuildRequestConfiguration.cs (hunk 1 above)
Comment (cdmihai) [reply src/Build/BackEnd/Shared/BuildRequestConfiguration.cs]: Moved discussion to https://github.com/microsoft/msbuild/pull/4379/files#r289095009. This change belongs to #4379.

File: src/Build/Resources/xlf/Strings.cs.xlf (hunk 2 above)
Comment (cdmihai) [reply src/Build/Resources/xlf/Strings.cs.xlf]: Moved to https://github.com/microsoft/msbuild/pull/4379/files#r289096539
