### PR TITLE
Compare strong names only when both assemblies are strong named

### LINKED ISSUE #1314: XmakeTasks nativemethods did not port clr implementation correcly.
The method RefToDef looks like it was supposed to be a copy of 
https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/vm/baseassemblyspec.cpp

However, in the implementation it is not returning false if the ref is strong named but dev is not strong named. 

This is causing the build of some of our project to fail due to a null reference exception happening in CompareRefToDef because def has no strong name and will be null when retrieved.

if (refStrongNamed) 
            { 
                 var defPkt = def.GetPublicKeyToken(); 
                bool defStrongNamed = defPkt != null && defPkt.Length != 0; 
               <Should return false here if defStrongNamed is false> 
 
                 return CompareRefToDef(@ref, def); 
          }

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes #1314

### CODE REVIEW

**Comment by cdmihai** [comment]
@crmann1

File: src/XMakeTasks/NativeMethods.cs [hunk 1]
```diff
@@ -1171,21 +1171,22 @@ internal static bool AllDrivesMapped()
...
-                return CompareRefToDef(@ref, def);
+                return IsStrongNamed(def) && CompareRefToDef(@ref, def);
             }
             else
             {
                 return @ref.Name.Equals(def.Name, StringComparison.OrdinalIgnoreCase);
             }
         }
 
+        private static bool IsStrongNamed(AssemblyName assembly)
```
Comment (rainersigwald) [inline src/XMakeTasks/NativeMethods.cs]: Is this what coreclr does? It wasn't immediately obvious from looking at their code. Link in comment?

**Comment by cdmihai** [comment]
@dotnet-bot test Windows_NT Build for Desktop please
