### PR TITLE
Fix broken directory build props unit tests on xplat

### LINKED ISSUE #806: DirectoryBuildPropsImportTests fail in xplat
All of these (new) tests fail with errors similar to the below. I think this is due to a confluence of 03d2b69b94f994d02d53a65379270202bbfa7dc2 and da283a7bea8a023c47cea73630fa3126c57b49a1, causing `Microsoft.Common.props` to not be present in the same place. I don't remember the context for that change from October--the right thing might be to undo it and restore the old placement. In the interests of expedience, I'm going to disable them.

@jeffkl When you get back can you take a look at this?

```
Microsoft.Build.UnitTests.DirectoryBuildPropsImportTests.DoesNotImportDirectoryBuildProjectWhenDisabled [FAIL]
      Microsoft.Build.Exceptions.InvalidProjectFileException : The imported project "O:\msbuild\bin\Debug-NetCore\Windows_NT_Deployment_Test\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\raines.NTDEV\AppData\Local\Temp\TempDirForMSBuildUnitTests\src\foo\foo.csproj
      Stack Trace:
         src\Shared\ProjectErrorUtilities.cs(441,0): at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
         src\Shared\ProjectErrorUtilities.cs(278,0): at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object arg0)
         src\Shared\ProjectErrorUtilities.cs(67,0): at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(2350,0): at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(2184,0): at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, List`1& projects, Boolean throwOnFileNotExistsError)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(2042,0): at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(1896,0): at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(1056,0): at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(786,0): at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
         src\XMakeBuildEngine\Evaluation\Evaluator.cs(392,0): at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
         src\XMakeBuildEngine\Definition\Project.cs(2122,0): at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
         src\XMakeBuildEngine\Definition\Project.cs(1556,0): at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary()
         src\XMakeBuildEngine\Definition\Project.cs(2170,0): at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
         src\XMakeBuildEngine\Definition\Project.cs(486,0): at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
         src\XMakeBuildEngine\Definition\Project.cs(430,0): at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
         src\XMakeBuildEngine\Definition\Project.cs(413,0): at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection)
         src\Shared\UnitTests\ObjectModelHelpers.cs(802,0): at Microsoft.Build.UnitTests.ObjectModelHelpers.LoadProjectFileInTempProjectDirectory(String projectFileRelativePath, Boolean touchProject)
         src\Shared\UnitTests\ObjectModelHelpers.cs(788,0): at Microsoft.Build.UnitTests.ObjectModelHelpers.LoadProjectFileInTempProjectDirectory(String projectFileRelativePath)
         src\XMakeTasks\UnitTests\DirectoryBuildProjectImportTestBase.cs(104,0): at Microsoft.Build.UnitTests.DirectoryBuildProjectImportTestBase.DoesNotImportDirectoryBuildProjectWhenDisabled()
```

### PR DESCRIPTION
**Pull request by jeffkl**
Re-enable DirectoryBuildProjectImportTests

    - Move Microsoft.Common.props back to the root
    - Update NUSPEC to get Microsoft.Common.props from the root and place it in an Extensions\15.0 directory
    - Fix problem where DirectoryBuildProjectImportTests on xplat was using a path with the wrong directory separators

Fixes #806

### CODE REVIEW

**Comment by jeffkl** [comment]
@rainersigwald @cdmihai this is now ready for review

**Comment by rainersigwald** [comment]
Nit: three bullet points in your PR description should mean three commits (or maybe 2 if the nuspec + moving props around changes are entertwined).

Nit: list `Fixes #806` in the commit message so it gets associated with the bug.

:shipit:

**Comment by jeffkl** [comment]
Yeah sorry we did so many things trying to troubleshoot this that my commit history got messed up so I squashed it...

File: src/XMakeTasks/UnitTests/DirectoryBuildProjectImportTestBase.cs [hunk 1]
```diff
@@ -20,7 +20,7 @@ abstract public class DirectoryBuildProjectImportTestBase : IDisposable
                     </PropertyGroup>
                 </Project>";
 
-        private const string ProjectRelativePath = @"src\foo\foo.csproj";
+        private readonly string _projectRelativePath = Path.Combine("src", "foo", "foo.csproj");
```
Comment (radical) [inline src/XMakeTasks/UnitTests/DirectoryBuildProjectImportTestBase.cs]: Is the field rename required? It doesn't match the style being used for private fields in this file.

Comment (jeffkl) [inline src/XMakeTasks/UnitTests/DirectoryBuildProjectImportTestBase.cs]: Yeah it went from a const to readonly because it's value is assigned at run time.  So technically the rename is necessary

---
In reply to: [76826798](https://github.com/Microsoft/msbuild/pull/974#discussion_r76826798) [](ancestors = 76826798)
