### PR TITLE
Normalize plugin paths before loading

### LINKED ISSUE #5080: MSBuild inconsistent file path to the same Task assembly load casing cast error
### Steps to reproduce

Failed to build https://github.com/dotnet-maestro-bot/cli/tree/merge/release/3.1.1xx-to-release/3.1.2xx due to error:

```
C:\work\cli\src\Microsoft.DotNet.MSBuildSdkResolver\Microsoft.DotNet.MSBuildSdkResolver.csproj]
C:\work\cli\.packages\microsoft.build.tasks.git\1.0.0-beta2-19367-01\buildCrossTargeting\Microsoft.Build.Tasks.Git.targets(24,5): error MSB4018: System.InvalidCastException: [A]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository] cannot be cast to [B]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository]. Type A originates from 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\work\cli\.dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Private.CoreLib.dll'. Type B originates from 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\work\cli\.dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Private.CoreLib.dll'. [C:\work\cli\src\Microsoft.DotNet.MSBuildSdkResolver\Microsoft.DotNet.MSBuildSdkResolver.csproj]
C:\work\cli\.packages\microsoft.build.tasks.git\1.0.0-beta2-19367-01\buildCrossTargeting\Microsoft.Build.Tasks.Git.targets(24,5): error MSB4018:    at Microsoft.Build.Tasks.Git.RepositoryTask.TryGetCachedRepositoryInstance(String cacheKey, Boolean requireCached, GitRepository& repository) in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 135 [C:\work\cli\src\Microsoft.DotNet.MSBuildSdkResolver\Microsoft.DotNet.MSBuildSdkResolver.csproj]
```

The same assembly with different path is loaded
image

It is caused by path in https://github.com/microsoft/msbuild/blob/86d9494e446de002ea6a4f08d6fbd111b1041059/src/Shared/CoreCLRAssemblyLoader.cs#L32 is not normalized.

### PR DESCRIPTION
**Pull request by rainersigwald**
Fixes #5080 by normalizing plugin assembly paths before deduplicating
loads based on those paths.

Does not fix the cross-assembly register/retrieve object problem #5084.

### CODE REVIEW

File: src/Build.UnitTests/BackEnd/AssemblyLoadContextTestTasks.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+using Microsoft.Build.Framework;
+using Microsoft.Build.Utilities;
+using System.Collections;
+using System.Collections.Generic;
+
+namespace AssemblyLoadContextTest
+{
+    public class RegisterObject : Task
+    {
+        internal const string CacheKey = "RegressionForMSBuild#5080";
```
Comment (Forgind) [inline src/Build.UnitTests/BackEnd/AssemblyLoadContextTestTasks.cs]: Do you always have to have CacheKeys like this and register them in Execute when introducing a new task for them to be used in MSBuild code?

Comment (rainersigwald) [reply src/Build.UnitTests/BackEnd/AssemblyLoadContextTestTasks.cs]: I don't understand the question. Can you elaborate?

Comment (Forgind) [reply src/Build.UnitTests/BackEnd/AssemblyLoadContextTestTasks.cs]: I was wondering what extra steps there are to let a task be called from MSBuild without a UsingTask element.
