### PR TITLE
Do not cause an error or failed build when logging an expanded condition

### LINKED ISSUE #2259: Condition-false logging can throw because it doesn't short-circuit
Given a project that has conditions that can be fully evaluated without evaluating every expression within them because of the short-circuit nature of AND and OR in the condition expression language:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))\init.props"
          Condition="'true' == 'false' AND '$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))' != ''" />
  <Target Name="Build">
    <Message Text="Build executed"
             Condition="'true' == 'false' AND '$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))' != ''"/>
  </Target>
</Project>
```

It's ok for `$(NonExistentProperty)` to expand to the empty string, even though that would cause an error evaluating `GetDirectoryNameOfFileAbove`, because the evaluator doesn't need that side of the expression to know the correct answer. A more realistic instance of this is something like `Condition="'$(EnlistmentRoot)' != '' AND '$([MSBuild]::GetDirectoryNameOfFileAbove($(EnlistmentRoot), init.props))' != '' "`.

The condition evaluator behaves correctly, but in some verbosities loggers will attempt to produce a string like `the condition {actual text from file} was evaluated as {text substituted with values}`, which attempts to run the right-hand side of the condition, which throws, failing the execution.

This has "always" been a problem (MSBuild 4 errors when executing the target from this test file), but is exacerbated by #2142, which causes the attempted full expansion of conditions on `<Import>` elements all the time. That is mitigated by #2225, so the increased problems now only occur when using the binary logger or opting into the logging behavior.

### PR DESCRIPTION
**Pull request by jeffkl**
In some cases, we evaluate a condition to false (which can be short circuited) but then expand the string fully.  The full condition can contain an error that wouldn't normally be seen if it evaluates to false early.

Fixes #2259

### CODE REVIEW

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs [hunk 1]
```diff
@@ -4385,6 +4385,38 @@ public void ThrownInvalidProjectExceptionProperlyHandled()
             }
         }
 
+        /// <summary>
+        /// Tests that an import, target, or task with a condition that contains an error but it short circuited does not fail the build.  This can happen when you have a condition like:
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]: "it short circuited" -> "is short-circuited"

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs [hunk 2]
```diff
@@ -4385,6 +4385,38 @@ public void ThrownInvalidProjectExceptionProperlyHandled()
...
+        /// 'true' == 'false' AND '$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))' != ''
+        /// 
+        /// The first condition is false so the second condition is not evaluated.  But in some cases we double evaluate the condition to log it.  The second evaluation will fail because it evaluates the whole string.
+        /// 
+        /// https://github.com/Microsoft/msbuild/issues/2259
+        /// </summary>
+        [Theory]
+        [InlineData("<Target Name=\"Build\" /><Import Project=\"$(NonExistentProperty)\" Condition=\"\'true\' == \'false\' And \'$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))\' != \'\'\" />")]
+        [InlineData("<Target Name=\"Build\" Condition=\"\'true\' == \'false\' And \'$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))\' != \'\'\" />")]
+        [InlineData("<Target Name=\"Build\"><Message Text=\"Build executed\" Condition=\"\'true\' == \'false\' And \'$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))\' != \'\'\" /></Target>")]
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]: What does the new message look like for each of these?

Comment (jeffkl) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]:
```
Target "Build" skipped, due to false condition; ('true' == 'false' And '$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))' != '') was evaluated as ('true' == 'false' And '[MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props)' != '').
```

```
Task "Message" skipped, due to false condition; ('true' == 'false' And '$([MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props))' != '') was evaluated as ('true' == 'false' And '[MSBuild]::GetDirectoryNameOfFileAbove($(NonExistentProperty), init.props)' != '').
```

Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]: Hmm. That's way better (thanks to not crashing) but I wonder if we could do even more. Would love to see it expand the arguments to the property function even if it can't to the function itself, so something like

`[MSBuild]::GetDirectoryNameOfFileAbove(, init.props)`

Think that's doable?

Comment (jeffkl) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]: Its possible for property functions, I've done this in bec1635

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs [hunk 3]
```diff
@@ -4385,6 +4385,38 @@ public void ThrownInvalidProjectExceptionProperlyHandled()
...
+        public void ConditionWithShortCircuitAndErrorDoesNotFailBuild(string projectInnerXml)
+        {
+            string content = ObjectModelHelpers.CleanupFileContents($@"
```
Comment (cdmihai) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs]: There's also a `Cleanup` extension method on strings.
